// Interpretacoes dos Ciclos Temporais (Ano Pessoal, Mes Pessoal e Dia Pessoal)
// Numeros 1 a 9 nos idiomas EN, PT e ES.
// Textos densos, ricos e psicologicamente precisos para orientacao estrategica.

export const YEARLY_FORECAST_INTERPRETATIONS: Record<'en' | 'pt' | 'es', Record<number, string>> = {
  en: {
    1: `Personal Year 1 inaugurates an entirely new 9-year evolutionary spiral for you, {name}. This is your cosmic springtime—a period characterized by decisive beginnings, raw initiative, and radical self-definition. The old chapter has closed; you are now handed a blank canvas upon which the themes of the next nine years will be inscribed.\n\nThe energetic mandate of this cycle demands courage, {name}, autonomy, and the willingness to break with obsolete allegiances. Seed new enterprises, take calculated risks, and place uncompromising trust in your own visionary instincts. Procrastination or waiting for external consensus during a 1-year delays your personal harvest.\n\nBeware only of impatience, {name}, and excessive self-isolation. Build your foundations with deliberate intention, honoring that while the seed must sprout through dark soil alone, its future fruit will sustain an entire community.`,

    2: `Personal Year 2 transitions for you, {name}, from the fiery solo push of the previous cycle into the receptive realm of patience, alliances, and organic gestation. This is not a year for brute-force conquest, but for diplomatic cultivation, fine-tuning details, and establishing deep cooperative bonds.\n\nThe vibrational current emphasizes emotional intelligence, {name}, behind-the-scenes negotiations, and the sensitive calibration of your relationships. Progress may feel subtle or slow on the surface, but beneath the visible ground, essential roots are drinking nourishment and anchoring your long-term stability.\n\nYour strategic task, {name}, is to master the art of conscious compromise without surrendering your self-worth. Practice peaceful discernment, avoid petty gossip, and nurture the alliances that will shelter your growth for years to come.`,

    3: `Personal Year 3 bursts forth for you, {name}, as a vibrant, solar cycle of creative blossoming, social circulation, and expressive expansion. The seeds planted in Year 1 and gestated in Year 2 now break through the surface into the light, demanding authentic visibility and joyful self-expression.\n\nYour communication, artistic flair, and natural magnetism are at an all-time high, {name}. Opportunities arrive through casual networking, public speaking, creative projects, and the fearless sharing of your ideas. The universe encourages you to bring color, humor, and levity into stagnant environments.\n\nGuard diligently against superficial dispersion, {name}, and nervous exhaustion. Channel your sparkling enthusiasm into substantive, finished creations rather than scattering your precious vital energy across fleeting social distractions.`,

    4: `Personal Year 4 is your sacred architect's year, {name}—a period of grounded discipline, systemic restructuring, and unyielding work ethic. Following the social ebullience of Year 3, this cycle calls you back to the drawing board to pour solid concrete beneath your dreams.\n\nThis is the optimal time, {name}, to secure finances, reorganize operational systems, invest in health, and formalize legal or professional agreements. Every ounce of methodical effort you invest this year creates an unshakeable fortress that will protect you during the rapid transformations of Year 5.\n\nDo not mistake the heavy workload for cosmic punishment, {name}; it is the necessary gravity that builds enduring legacy. Keep your focus on long-term endurance, resist shortcuts, and take quiet pride in craftsmanship.`,

    5: `Personal Year 5 acts as the great evolutionary pivot of your 9-year cycle, {name}. The structures established in Year 4 are now tested, dynamically reconfigured, or blasted open by the exhilarating winds of freedom, adventure, and unexpected transformation.\n\nExpect sudden pivots, travel, shifts in routine, and encounters, {name}, that broaden your intellectual and geographical horizons. This is a cycle designed to liberate you from calcified habits and stale routines. Your adaptability is your greatest asset; lean into the unexpected with curiosity rather than fear.\n\nYour primary caution, {name}, is avoiding reckless hedonism or impulsive sabotage. Exercise freedom with mature discernment, steering your sails deliberately through the shifting winds rather than letting the gale blow you off course.`,

    6: `Personal Year 6 brings your intense focus back to the hearth, {name}, intimate partnerships, domestic harmony, and community responsibility. After the wild freedom of Year 5, your soul is drawn into the sacred duties of love, family care, and restorative beauty.\n\nThis is a premier cycle for marriage, home renovation, healing long-standing family fractures, and stepping into positions of mentorship or civic guardianship, {name}. Your empathy and aesthetic taste are profoundly heightened, calling you to beautify your environment and offer refuge to those in need.\n\nBeware of shouldering burdens that do not belong to you, {name}, or playing the self-sacrificing martyr. Practice balanced caregiving: pour love generously while maintaining firm, loving boundaries around your own emotional sanctuary.`,

    7: `Personal Year 7 marks a sacred sabbatical of your soul, {name}—a quiet, contemplative cycle dedicated to self-knowledge, spiritual recalibration, and intellectual deepening. The cosmic current pulls inward, asking you to withdraw from superficial social competition to hear your inner voice.\n\nThis is a peerless year, {name}, for research, writing, deep therapeutic healing, mystical study, and solitary retreat in nature. Material ambitions may temporarily pause or feel less urgent, as your psyche undergoes a profound reorganization of core values and philosophical truth.\n\nResist the impulse to force outer expansion, {name}, or succumb to cynical isolation. Trust the sacred timing of withdrawal; the profound insights you harvest in this quiet sanctuary will serve as the guiding light for the triumph of Year 8.`,

    8: `Personal Year 8 is your harvest cycle of material achievement, executive power, and karmic manifestation, {name}. The deliberate labor, spiritual alignment, and patient endurance of the past seven years now culminate in tangible authority, financial reward, and worldly recognition.\n\nDoors swing open, {name}, in the realms of business, investment, leadership, and public influence. You are called to step into the fullness of your sovereign competence, commanding projects with bold resolve and clear moral vision. You understand the laws of cause and effect with surgical lucidity.\n\nYour highest challenge, {name}, is wielding power without arrogance. When your financial and material ambitions are married to ethical integrity and collective upliftment, your harvest becomes a lasting legacy of dignified prosperity.`,

    9: `Personal Year 9 represents the grand culmination, closure, and sacred clearance of your entire 9-year cycle, {name}. This is an autumn of the soul: a time to reap what remains, release what is obsolete, and forgive old grievances to prepare the soil for a new dawn.\n\nYou may experience the natural dissolving of relationships, jobs, or belief systems, {name}, that have completed their evolutionary purpose. Attempting to cling to the past during a 9-year only generates unnecessary friction; practice graceful surrender and compassionate detachment.\n\nDirect your energy, {name}, toward philanthropy, artistic synthesis, and universal generosity. As you clear out the energetic clutter of the past nine years with gratitude, you create pure, fertile space for the brand-new cycle that awaits you next year.`,
  },
  pt: {
    1: `O Ano Pessoal 1 inaugura uma nova espiral evolutiva de 9 anos. Este é o seu tempo de semeadura primordial: um ciclo caracterizado por novos começos audaciosos, iniciativa soberana e redefinição radical da sua própria identidade. A página anterior foi virada; você tem nas mãos uma tela em branco onde os próximos nove anos serão desenhados.\n\nA exigência vibracional deste período é de coragem, autonomia e desapego de antigas muletas. É o momento perfeito para inaugurar projetos autorais, assumir riscos calculados e confiar na própria visão sem esperar a validação alheia. A hesitação durante um Ano 1 atrasa a colheita de todo o ciclo.\n\nSeu único cuidado deve ser evitar a precipitação impaciente e a agressividade no trato. Construa seus passos com firmeza consciente, sabendo que a semente que brota no solo escuro logo se tornará a árvore que abrigará o seu futuro.`,

    2: `O Ano Pessoal 2 desacelera o ritmo explosivo do ano anterior para conduzi-lo ao território fértil da cooperação, da paciência e da maturação silenciosa. Este não é um período de conquistas pela força bruta, mas de diplomacia refinada, consolidação de alianças e harmonização de detalhes essenciais.\n\nA corrente energética favorece a inteligência relacional, negociações sensíveis e o cuidado com parcerias e vínculos de longo prazo. O progresso pode parecer mais sutil à primeira vista, mas abaixo da superfície as raízes mais profundas estão se fixando no solo para sustentar o seu crescimento.\n\nSua tarefa estratégica é cultivar a arte do diálogo sem anular suas próprias vontades. Pratique a escuta atenta, evite intrigas desnecessárias e fortaleça os laços afetivos e profissionais que acompanharão sua jornada pelos próximos anos.`,

    3: `O Ano Pessoal 3 irrompe como uma celebração solar de expansão criativa, comunicação aberta e circulação social vibrante. A semente plantada no Ano 1 e cuidada no Ano 2 agora rompe a terra e se abre em flor, exigindo visibilidade autêntica e alegria de viver.\n\nSeu carisma pessoal, magnetismo e expressividade estão no ápice. Oportunidades preciosas chegam através de encontros casuais, exposições públicas, escrita, arte e compartilhamento generoso das suas ideias. É o momento cósmico de colorir o mundo e renovar o ânimo.\n\nCuidado apenas para não dispersar sua energia em excesso de compromissos vazios ou futilidades. Canalize seu brilho verbal e criativo em projetos concretos e duradouros, evitando o desperdício das suas melhores forças em entretenimentos efêmeros.`,

    4: `O Ano Pessoal 4 é o ciclo do mestre arquiteto: um período de disciplina rigorosa, consolidação estrutural e esforço paciente. Após a leveza expansiva do Ano 3, este ano o convoca para o canteiro de obras, onde você deve assentar os alicerces definitivos dos seus sonhos.\n\nÉ o momento propício para organizar suas finanças, estabelecer rotinas saudáveis, formalizar contratos e aprimorar métodos operacionais. Cada hora de trabalho metódico dedicada neste ciclo constrói a fortaleza inabalável que protegerá você durante as tempestades e mudanças do Ano 5.\n\nNão encare a exigência de esforço como um fardo, mas como o teste sagrado que forja mestres. Mantenha o foco nos resultados de longo prazo, evite atalhos duvidosos e tenha orgulho da solidez que suas mãos estão erguendo.`,

    5: `O Ano Pessoal 5 atua como o grande divisor de águas da sua espiral de 9 anos. As estruturas consolidadas no Ano 4 são agora desafiadas, oxigenadas e revolucionadas pelos ventos elétricos da liberdade, da aventura e das mudanças inesperadas.\n\nPrepare-se para viagens, guinadas de rumo, novas conexões e surpresas que expandirão sua visão de mundo. Este ciclo existe para libertar você de rotinas estéreis e crenças limitantes. Sua maior virtude agora é a adaptabilidade inteligente: receba o novo com curiosidade e coragem.\n\nSeu maior ponto de atenção é não cair na armadilha da impulsividade irresponsável ou da fuga desgovernada. Exerça sua liberdade com propósito e maturidade, manobrando o leme da sua vida em meio aos ventos velozes em vez de se deixar arrastar por qualquer rajada.`,

    6: `O Ano Pessoal 6 traz o foco de volta para o coração, os relacionamentos íntimos, a harmonia do lar e a responsabilidade comunitária. Após a agitação libertária do Ano 5, sua alma sente o chamado doce e solene de cuidar dos que você ama e construir santuários de paz.\n\nEste é um ciclo extraordinário para casamentos, gravidez, reformas domésticas, resolução de antigas feridas familiares e liderança comunitária acolhedora. Sua sensibilidade estética e senso de justiça estão aguçados, impulsionando você a embelezar a vida ao seu redor.\n\nCuidado apenas para não assumir os problemas de todos ou se sacrificar de forma amargurada. Ame com sabedoria: ofereça apoio generoso, mas preserve limites sagrados para que seu próprio templo emocional permaneça nutrido e sereno.`,

    7: `O Ano Pessoal 7 representa um sábado sagrado para a sua alma: um ciclo de introspecção profunda, estudo, refinamento espiritual e silêncio fértil. A corrente cósmica convida você a desacelerar a corrida pelo mundo material para escutar a voz da sua consciência interior.\n\nÉ o período mais nobre para aprofundar estudos científicos ou esotéricos, fazer terapia, escrever, meditar e buscar retiros restauradores na natureza. Os avanços exteriores podem parecer pausados, mas uma reestruturação profunda e indispensável de crenças e valores está operando dentro de você.\n\nEvite forçar a expansão mundana ou cair em isolamentos amargos. Confie na sabedoria da quietude; os tesouros de clareza e paz que você lapidar neste ano serão a base indispensável para as grandes conquistas materiais do Ano 8.`,

    8: `O Ano Pessoal 8 é o ciclo da colheita suprema, da liderança executiva e da consolidação do poder material. Todo o esforço dedicado, os estudos acumulados e as provações superadas ao longo dos últimos sete anos agora se convertem em reconhecimento prático, solidez financeira e autoridade.\n\nPortas grandiosas se abrem no universo dos negócios, da carreira, de investimentos e de grandes decisões institucionais. Você é convocado a liderar com dignidade e firmeza, comandando recursos e pessoas com justiça incorruptível e visão estratégica de longo alcance.\n\nSeu maior teste é manter a humildade e a ética no auge do sucesso. Quando sua busca pela prosperidade se traduz em geração de valor para a sociedade, seu triunfo material se eterniza como um legado honroso de prosperidade limpa.`,

    9: `O Ano Pessoal 9 marca a apoteose, o fechamento e a limpeza definitiva de todo o ciclo de 9 anos. Este é o outono da alma: o momento de desapegar do que cumpriu seu papel, perdoar mágoas antigas e preparar o solo do seu ser para um novo renascimento.\n\nÉ natural vivenciar o encerramento sereno de contratos, amizades, ciclos profissionais ou formas de pensar desgastadas. Tentar reter o passado durante um Ano 9 só gera angústia desnecessária; acolha os finais como bênçãos libertadoras que abrem caminho para o novo.\n\nDedique-se à caridade, à arte, à generosidade sem cobranças e à celebração das lições aprendidas. Ao esvaziar sua bagagem com gratidão e compaixão, você cria o espaço sagrado onde florescerá o próximo grande ciclo da sua vida.`,
  },
  es: {
    1: `El Año Personal 1 inaugura una espiral evolutiva inédita de 9 años. Es tu primavera cósmica: un período de inicios audaces, soberanía recobrada y refundación de tu identidad vital. Se ha pasado la página; tienes ante ti un lienzo en blanco donde se inscribirá la pauta de los próximos nueve años.\n\nLa directriz energética de este ciclo reclama coraje, autonomía y ruptura con viejas muletas. Siembra proyectos ambiciosos, asume riesgos calculados y fía tu destino a tu instinto creador sin aguardar el beneplácito ajeno. La vacilación en un Año 1 demorará la cosecha de todo el ciclo.\n\nModera únicamente la impaciencia y el aislamiento orgulloso. Avanza con serenidad consciente, sabiendo que la semilla que rompe la tierra en soledad terminará cobijando a muchos bajo sus ramas.`,

    2: `El Año Personal 2 apacigua el empuje fogoso del año previo para invitarte al territorio de la paciencia, las alianzas y la gestación invisible. No es momento de embates frontales, sino de diplomacia sutil, ajuste de detalles y cultivo de lazos leales.\n\nLa corriente resalta la inteligencia emocional, los pactos discretos y la escucha empática. Quizá el avance parezca imperceptible en la superficie, pero bajo el suelo las raíces más hondas se afianzan para garantizar tu estabilidad futura.\n\nTu cometido estratégico es aprender a ceder sin desdibujarte. Practica la tolerancia, esquiva disputas estériles y afianza las amistades y sociedades que te ampararán a lo largo de los años venideros.`,

    3: `El Año Personal 3 irrumpe como un ciclo jubiloso de florecimiento creador, visibilidad pública y animación relacional. Lo sembrado en el Año 1 y templado en el Año 2 asoma con fuerza a la luz, reclamando autenticidad y alegría de vivir.\n\nTu carisma, elocuencia y don estético se hallan en plenitud. Las oportunidades llamarán a tu puerta a través de la tertulia distendida, la oratoria, el arte y la comunicación generosa de tus ideas. Es tiempo de avivar los ánimos y disipar rigideces con tu entusiasmo.\n\nEvita la dispersión vana y el cansancio nervioso. Vierte tu talento en obras acabadas y sustantivas en lugar de malgastar tus dones en aplausos efímeros o compromisos superficiales.`,

    4: `El Año Personal 4 es el año del alarife: un tiempo de disciplina austera, reorganización pragmática y labor perseverante. Pasada la ligereza del Año 3, este ciclo te conduce al taller para dotar de cimientos inamovibles a tus aspiraciones.\n\nEs el ciclo ideal para afianzar tu economía, sanear rutinas, perfeccionar métodos y blindar convenios legales. Cada esfuerzo metódico depositado ahora erige la fortaleza que te resguardará de los vaivenes que deparará el Año 5.\n\nNo juzgues el rigor como un lastre, sino como la fragua que corona a los maestros. Apunta a la longevidad de los frutos, desestima atajos y enorgullécete de la solidez que van alzando tus manos.`,

    5: `El Año Personal 5 constituye el gran gozne transformador de tu ciclo novenario. El orden fijado en el Año 4 se ve ahora sacudido, oxigenado y renovado por los vientos vivificantes de la aventura, la mudanza y lo imprevisto.\n\nAguardan giros repentinos, viajes, nuevos vínculos y coyunturas que ensancharán tu criterio. Este ciclo te emancipa de inercias agostadas. Tu herramienta más valiosa es la ductilidad inteligente: abraza la novedad sin zozobra.\n\nTu mayor cuidado es no precipitarte en la insensatez o la fuga atolondrada. Gobierna tu albedrío con sensatez, dirigiendo el rumbo en medio de la ventolera en vez de dejarte arrastrar por el temporal.`,

    6: `El Año Personal 6 devuelve la mirada al corazón, el nido doméstico y el servicio hacia los tuyos. Tras la intemperie del Año 5, tu espíritu reclama la dulzura de la reconciliación, el embellecimiento del entorno y el amparo afectivo.\n\nEs un año venturoso para contraer nupcias, agrandar la prole, remozar la morada, saldar viejos rencores familiares y abrazar labores comunitarias. Tu sensibilidad moral y buen gusto te impulsan a convertir cualquier espacio en un remanso de sosiego.\n\nNo caigas en el agobio de cargar con aflicciones ajenas ni en el reproche martirizado. Prodigar cuidado exige también preservar tu templo interior con ternura y límites claros.`,

    7: `El Año Personal 7 constituye el retiro sabático del espíritu: un remanso fecundo consagrado a la introspección, la meditación y el estudio riguroso. La corriente cósmica te convoca a moderar el trajín mundano para afinar el oído ante la voz de tu conciencia.\n\nEs el período supremo para ahondar en saberes trascendentes, escribir, someterte a terapia y buscar la quietud de la naturaleza. Lo material parecerá ralentizarse, mas en tu fuero interno se está gestando una lúcida clarificación de valores.\n\nNo pugnes por forzar expansiones exteriores ni caigas en la amargura solitaria. Ten fe en el reposo; las certezas que atesores este año serán la palanca de tus conquistas en el Año 8.`,

    8: `El Año Personal 8 es el tiempo de la gran vendimia material, el mando ejecutivo y la justicia cármica. La disciplina, el saber adquirido y los sacrificios de los siete años precedentes cristalizan ahora en prestigio, solvencia patrimonial y rango.\n\nSe ensanchan las avenidas en el ámbito de las finanzas, el liderazgo institucional y los proyectos mayúsculos. Estás emplazado a capitanear con nobleza, administrando voluntades y haberes con honradez inquebrantable y cálculo certero.\n\nTu prueba suprema es moderar el poderío con la piedad. Cuando tu éxito redunda en progreso para la comunidad, tu logro terrenal se transforma en un patrimonio venerable y limpio.`,

    9: `El Año Personal 9 corona la culminación y clausura de toda tu trayectoria de 9 años. Es el otoño del alma: momento de recolectar lo último, soltar amarras desgastadas y perdonar agravios para fecundar el terreno de un renacer inminente.\n\nPresenciarás el término natural de etapas profesionales, amistades o convicciones caducas. Retener el pretérito en este año solo acarrea desazón; despídete de lo cumplido con gratitud y serenidad.\n\nConságrate a la caridad, al arte desinteresado y a la síntesis existencial. Al aligerar tu equipaje con desprendimiento, consagras el templo limpio donde germinará tu próximo ciclo vital.`,
  },
};

export const MONTHLY_FORECAST_INTERPRETATIONS: Record<'en' | 'pt' | 'es', Record<number, (monthName: string) => string>> = {
  en: {
    1: (m) => `The month of ${m} introduces a sharp, pioneering vibration for you, {name}, that demands personal initiative and autonomous decision-making. The atmospheric energy supports launching projects, establishing clean boundaries, and taking command of stalled situations.\n\nFocus your attention, {name}, on decisive beginnings rather than waiting for external approval. Clear away self-doubt, assert your genuine priorities, and trust that proactive movement now sets an empowering tone for the upcoming season.`,

    2: (m) => `The month of ${m} softens your outer tempo, {name}, bringing relationships, diplomatic patience, and behind-the-scenes cooperation into sharp focus. This is a period where attentive listening and tactful negotiation accomplish far more than brute force.\n\nCultivate your key alliances with care, {name}, and attend to subtle emotional dynamics. Avoid hasty ultimatums; trust that allowing circumstances to gestate organically will yield far more resilient agreements.`,

    3: (m) => `The month of ${m} expands your social circulation, communicative magnetism, and creative self-expression, {name}. Ideas flow with spontaneous agility, and conversations carry an infectious spark of enthusiasm and optimism.\n\nTake advantage of this vibrant window, {name}, to pitch ideas, express heartfelt sentiments, and explore artistic outlets. Simply ensure that your social ebullience remains anchored in genuine substance and finished commitments.`,

    4: (m) => `The month of ${m} establishes a pragmatic rhythm for you, {name}, demanding operational discipline, attention to detail, and methodical focus. The cosmic current asks you to organize schedules, review financial budgets, and strengthen fundamental systems.\n\nApproach your duties with patience and craftsmanship, {name}. The methodical labor you invest right now lays down the reliable bedrock that protects your progress from future disruption.`,

    5: (m) => `The month of ${m} delivers an electric wave of dynamism, unexpected pivots, and a thirst for personal liberation, {name}. Stagnant routines are shaken up, inviting you to adapt swiftly and embrace new perspectives or environments.\n\nRemain fluid in the face of shifting schedules, {name}, and welcome spontaneous opportunities for adventure. Channel your heightened curiosity constructively, avoiding reckless impulses while enjoying fresh horizons.`,

    6: (m) => `The month of ${m} brings domestic harmony, emotional reconciliations, and communal responsibilities to the center of your awareness, {name}. Matters involving family, home improvements, and aesthetic beauty call for your caring stewardship.\n\nDedicate quality time, {name}, to listening to loved ones and cultivating comfort in your immediate sanctuary. Balance generous devotion with healthy personal boundaries to keep your own spirit refreshed.`,

    7: (m) => `The month of ${m} invites a sacred pause for you, {name}, for contemplative study, introspective self-knowledge, and mental refinement. The outward rush subsides to allow deeper philosophical insights and intuitive clarity to emerge.\n\nGive yourself permission, {name}, to enjoy quiet solitude, immersion in nature, or focused research. Trust your inner compass over external chatter, allowing quiet contemplation to reveal solutions that logic alone could not find.`,

    8: (m) => `The month of ${m} activates a powerful current of executive ambition, material organization, and strategic negotiations for you, {name}. Professional matters and financial decisions accelerate, requiring confident leadership and fair judgment.\n\nStep boldly into your authority, {name}, and negotiate from a stance of self-worth and integrity. Ground your ambitious goals in ethical clarity, ensuring that your achievements build sustainable prosperity.`,

    9: (m) => `The month of ${m} marks a period of cyclic culmination, conscious release, and emotional resolution for you, {name}. Loose ends in personal or professional spheres seek closure, urging you to declutter what no longer serves your path.\n\nPractice compassionate forgiveness, {name}, and serene detachment. By tying up pending matters and letting go of outgrown expectations with gratitude, you make ready for the fresh influx soon to follow.`,
  },
  pt: {
    1: (m) => `O mês de ${m} introduz uma vibração pioneira e incisiva, exigindo iniciativa própria e decisões corajosas. A energia cósmica favorece inaugurar projetos, estabelecer limites saudáveis e assumir o leme de situações que estavam estagnadas.\n\nConcentre suas forças em agir em vez de esperar aprovação alheia. Dissipe dúvidas internas, afirme suas prioridades autênticas e confie que sua atitude proativa agora abrirá portas duradouras para os próximos meses.`,

    2: (m) => `O mês de ${m} desacelera a pressa exterior, colocando em primeiro plano a cooperação, a paciência diplomática e a harmonia relacional. É um tempo em que a escuta atenta e o tato valem infinitamente mais do que imposições duras.\n\nCultive suas parcerias com carinho e atente-se às entrelinhas emocionais das pessoas ao redor. Evite confrontos precipitados; saiba que deixar as situações amadurecerem no próprio tempo trará acordos muito mais sólidos.`,

    3: (m) => `O mês de ${m} expande sua vida social, magnetismo comunicativo e criatividade espontânea. Suas ideias ganham leveza e entusiasmo, tornando suas palavras cativantes e inspiradoras para quem o escuta.\n\nAproveite esta janela favorável para apresentar projetos, compartilhar sentimentos e investir na sua expressão artística. Cuide apenas para que seu entusiasmo efervescente se converta em entregas concretas, evitando dispersão.`,

    4: (m) => `O mês de ${m} estabelece um ritmo sóbrio que pede foco prático, organização metódica e disciplina inabalável. O momento convida a colocar a casa em ordem: organizar finanças, revisar rotinas e aperfeiçoar processos de trabalho.\n\nEncare suas tarefas com paciência e capricho. O esforço bem direcionado que você plantar neste mês servirá de alicerce inabalável para proteger suas conquistas contra qualquer turbulência futura.`,

    5: (m) => `O mês de ${m} traz uma onda dinâmica de renovação, surpresas no cotidiano e sede de movimento. Padrões engessados tendem a ser sacudidos, abrindo espaço para mudanças de rotina, viagens ou novas perspectivas intelectuais.\n\nMantenha a mente flexível diante de alterações de planos e abrace o novo com curiosidade. Use essa energia efervescente com maturidade, evitando atitudes impensadas e desfrutando da liberdade de evoluir.`,

    6: (m) => `O mês de ${m} convoca sua atenção para o coração, o bem-estar familiar e a harmonia do ambiente doméstico. Assuntos ligados a afeto, reformas no lar e acolhimento dos que você ama ganham importância máxima.\n\nDedique tempo de qualidade aos seus vínculos queridos e cuide de criar aconchego no seu espaço íntimo. Lembre-se apenas de cuidar dos outros sem esquecer de si mesmo, sustentando limites amorosos.`,

    7: (m) => `O mês de ${m} convida a uma pausa sagrada de recolhimento, estudo aprofundado e refinamento espiritual. A agitação cotidiana perde força para que você possa escutar com nitidez a sabedoria da sua alma.\n\nReserve momentos para a solitude lúcida, leituras transformadoras ou contato com a natureza. Não force acontecimentos no mundo exterior; permita que as respostas mais lúcidas amadureçam no silêncio da sua reflexão.`,

    8: (m) => `O mês de ${m} ativa um impulso vigoroso de realização material, autoridade profissional e foco estratégico. Negociações importantes, decisões financeiras e projetos de carreira ganham velocidade e exigem postura firme.\n\nAssuma sua competência sem timidez e faça valer o seu valor com justiça e clareza. Una a ambição construtiva a princípios éticos sólidos, garantindo que o progresso conquistado seja seguro e respeitado.`,

    9: (m) => `O mês de ${m} marca um ciclo de conclusões serenas, desapego maduro e faxina emocional. Assuntos pendentes pedem desfecho definitivo, convidando você a deixar para trás o que já não cabe na sua caminhada.\n\nPratique o perdão sincero e a generosidade desinteressada. Ao finalizar etapas desgastadas com leveza e gratidão, você limpa o terreno da sua vida para acolher as novidades que logo virão.`,
  },
  es: {
    1: (m) => `El mes de ${m} introduce una vibración pionera y resuelta que reclama iniciativa propia y elecciones audaces. El influjo cósmico ampara el despegue de proyectos, la clarificación de límites y el timón firme ante lo que yacía estancado.\n\nEnfoca tus bríos en la acción decidida sin esperar la venia ajena. Despeja vacilaciones, reafirma tus metas nucleares y confía en que tu empuje actual asentará un rumbo de soberanía para los tiempos por venir.`,

    2: (m) => `El mes de ${m} atempera la prisa exterior, trayendo a primer plano los acuerdos, la paciencia diplomática y la armonía con los demás. Es un ciclo en el que la escucha comprensiva y la prudencia rinden frutos más nobles que cualquier empeño forzado.\n\nCuida con esmero tus alianzas y descifra los matices afectivos de tu entorno. Huye de discusiones precipitadas; comprende que permitir que los acontecimientos maduren a su ritmo asegurará pactos mucho más firmes.`,

    3: (m) => `El mes de ${m} dilata tu desenvolvimiento social, tu carisma verbal y tu inventiva creadora. Las ideas brotan con amenidad, y las conversaciones se impregnan de un dinamismo contagioso y esperanzador.\n\nAprovecha este marco favorable para divulgar propuestas, expresar tus afectos y volcarte en tus dones estéticos. Vigila únicamente que tu agudeza se traduzca en obras tangibles, eludiendo la dispersión estéril.`,

    4: (m) => `El mes de ${m} impone un compás circunspecto que exige disciplina metódica, sobriedad y tenacidad inquebrantable. El momento apremia a sanear tus cuentas, reordenar faenas cotidianas y consolidar procedimientos laborales.\n\nEncarar tus obligaciones con rigor y pulcritud es tu mejor baza. El trabajo concienzudo que consolides en este ciclo obrará como un baluarte invulnerable ante cualquier contingencia venidera.`,

    5: (m) => `El mes de ${m} desata una marea dinámica de mudanzas, giros imprevistos y sed de renovación. Las pautas rígidas tienden a tambalearse, brindando margen para variaciones de itinerario, viajes o enfoques intelectuales frescos.\n\nConserva una mente dúctil ante los cambios de planes y recibe lo inédito con entusiasmo. Emplea este vigor con templanza, evitando desatinos impulsivos y gozando de la facultad de transformarte con lucidez.`,

    6: (m) => `El mes de ${m} reconduce tu sensibilidad hacia el seno familiar, los lazos cordiales y el decoro de tu hogar. Las cuestiones ligadas al afecto, la compostura de la morada y el amparo de los tuyos reclaman tu mirada atenta.\n\nConsagra tiempo de calidad a tus vínculos dilectos y procura paz en tu intimidad. Recuerda velar por el prójimo sin descuidar tu propio templo, manteniendo límites tiernos pero innegociables.`,

    7: (m) => `El mes de ${m} suscita una pausa sagrada de sosiego, indagación honda y recogimiento espiritual. El ajetreo mundano mengua para que logres percibir con pureza la voz sosegada de tu sabiduría interior.\n\nDispón instantes de soledad fecunda, lecturas ennoblecedoras o comunión con la naturaleza. No violentes los plazos del mundo; aguarda a que las resoluciones más preclaras amanezcan en el silencio de tu mente.`,

    8: (m) => `El mes de ${m} aviva un empuje resuelto de conquista material, autoridad profesional y lucidez estratégica. Asuntos económicos de peso y decisiones laborales cobran vigor, reclamando aplomo y temple justo.\n\nAsume tu jerarquía sin timidez y haz valer tu capacidad con rectitud y transparencia. Acompasa la ambición decidida con la honradez de espíritu, asegurando que tu progreso sea venerable y firme.`,

    9: (m) => `El mes de ${m} señala un hito de resoluciones compasivas, despedida madura y purificación emocional. Aquello que ha rendido su fruto pide conclusión, exhortándote a despojarte de cuanto ya no enriquece tu destino.\n\nEjerce el perdón generoso y el desprendimiento sereno. Al cerrar ciclos marchitos con paz y gratitud, despejas el horizonte vital para abrazar las bienaventuranzas que ya se avecinan.`,
  },
};

export const DAILY_FORECAST_INTERPRETATIONS: Record<'en' | 'pt' | 'es', Record<number, string>> = {
  en: {
    1: `A day charged with pioneering clarity, fresh initiatives, and assertive autonomy for you, {name}. The cosmos strongly favors making bold decisions, stepping out of waiting mode, and cutting through stagnation with decisive personal action.\n\nTrust your instinct over consensus today, {name}. Stand tall in your authentic sovereignty, initiate that important step, and let your leadership set the standard for your environment.`,

    2: `A day governed by subtle relational currents, receptive listening, and diplomatic tact, {name}. Progress today is achieved not through confrontation, but through patient dialogue, mediation, and behind-the-scenes cultivation.\n\nKeep your inner calm intact, {name}. Pay close attention to unspoken signals, seek mutual understanding, and allow agreements to mature without rushing.`,

    3: `A day vibrating with creative spark, social charisma, and spontaneous verbal brilliance for you, {name}. Your expressive powers are heightened, making this an ideal moment to share ideas, resolve misunderstandings with humor, and embrace lighthearted joy.\n\nLet your authentic enthusiasm radiate freely, {name}. Connect with friends, pitch creative visions, and allow your natural charm to melt away unnecessary tension.`,

    4: `A day grounded in practical realism, methodical discipline, and structural organization, {name}. The vibrational climate demands attention to detail, administrative follow-through, and pragmatic execution.\n\nTackle tedious tasks, {name}, with quiet pride in craftsmanship. Establishing order in your physical and financial spaces today brings immediate peace of mind and long-term security.`,

    5: `A day energized by swift movement, unexpected twists, and dynamic flexibility, {name}. The energetic currents resist rigid plans, inviting you to pivot with curiosity and seize unexpected opportunities.\n\nStay adaptable and open-minded, {name}. Embrace surprises as welcome catalysts for renewal, taking care only to direct your restless energy with conscious intention.`,

    6: `A day centered on hearth, domestic warmth, and restorative love for you, {name}. Your focus turns naturally toward family, dear friends, and creating beauty and comfort in your living environment.\n\nOffer support, {name}, listen deeply to loved ones, and beautify your surroundings. Remember that true nurturing begins with honoring your own peace of mind.`,

    7: `A day dedicated to reflective silence, analytical discernment, and spiritual self-knowledge, {name}. The outer world may feel loud; your greatest strength lies in taking a step back into quiet observation.\n\nHonor your need for solitude and contemplative study, {name}. Avoid impulsive decisions, immerse yourself in deep thinking, and trust the intuitive revelations that surface in stillness.`,

    8: `A day of executive command, material focus, and high-stakes clarity for you, {name}. The atmosphere demands professional confidence, financial prudence, and grounded leadership in the physical realm.\n\nStep into your authority with integrity, {name}. Negotiate terms, organize investments, and make pragmatic choices that advance your long-term sovereignty.`,

    9: `A day of culmination, generous forgiveness, and conscious release, {name}. This is an ideal cosmic window for concluding pending matters, clearing out physical and mental clutter, and letting go of old grudges.\n\nRelease with an open heart, {name}. What is released today clears sacred space for the vibrant new cycles waiting to dawn on your horizon.`,
  },
  pt: {
    1: `Um dia carregado de clareza pioneira, novos impulsos e liderança autônoma. O cosmos favorece decisões corajosas, sair da inércia e cortar a procrastinação com atitude firme e assertiva.\n\nConfie na sua intuição acima de palpites alheios. Assuma sua soberania, dê o primeiro passo naquele assunto adiado e lidere pelo exemplo.`,

    2: `Um dia regido por percepções sutis, escuta atenta e diplomacia nas relações. As vitórias de hoje não vêm pelo confronto, mas pela moderação, pela paciência e pelos acordos nos bastidores.\n\nPreserve sua serenidade. Atente-se às entrelinhas, busque pontos de convergência e permita que os entendimentos amadureçam sem pressa.`,

    3: `Um dia vibrante de criatividade, carisma comunicativo e espontaneidade. Sua palavra ganha magnetismo e leveza, tornando o momento ideal para expor ideias, quebrar tensões com bom humor e cultivar alegria genuína.\n\nDeixe seu entusiasmo contagiar os ambientes. Conecte-se com pessoas queridas, compartilhe visões e permita que sua inteligência relacional abra novos caminhos.`,

    4: `Um dia ancorado em realismo prático, foco metódico e organização disciplinada. A vibração exige atenção aos detalhes, cumprimento rigoroso de deveres e estruturação da rotina.\n\nEncare tarefas complexas com paciência de construtor. Colocar ordem na vida material e financeira hoje trará alívio imediato e estabilidade duradoura.`,

    5: `Um dia energizado por dinamismo, surpresas e necessidade de flexibilidade mental. Os planos rígidos tendem a mudar, convidando você a se adaptar com agilidade e inteligência às novidades.\n\nMantenha o espírito curioso e aberto ao inesperado. Abrace os imprevistos como oportunidades de aprendizado, canalizando a inquietação em movimento construtivo.`,

    6: `Um dia voltado para o acolhimento, harmonia familiar e equilíbrio emocional. Seu coração se volta para o bem-estar das pessoas queridas e para o embelezamento do seu espaço íntimo.\n\nOfereça afeto sincero, pratique a reconciliação e cuide do seu lar. Lembre-se de que a verdadeira generosidade começa em respeitar o seu próprio descanso.`,

    7: `Um dia de recolhimento reflexivo, estudo aprofundado e intuição refinada. O ritmo externo pode parecer ruidoso demais; seu maior refúgio hoje é o silêncio e a auto-observação serena.\n\nHonre sua necessidade de momentos a sós. Evite decisões precipitadas, aprofunde seus conhecimentos e confie nas respostas que surgem na quietude da sua mente.`,

    8: `Um dia de autoridade executiva, foco material e decisões de impacto prático. O clima convoca postura firme nos negócios, visão estratégica e organização dos recursos com responsabilidade.\n\nAssuma sua competência com serenidade e justiça. Conduza negociações com clareza e tome as atitudes necessárias para consolidar sua independência material.`,

    9: `Um dia de fechamentos serenos, perdão generoso e desapego libertador. O momento é perfeito para concluir pendências antigas, doar o que não usa mais e esvaziar a mente de mágoas passadas.\n\nDesapegue com gratidão. O que você encerra com serenidade hoje abre espaço limpo e sagrado para os novos começos que logo se apresentarão.`,
  },
  es: {
    1: `Una jornada impregnada de brío pionero, nuevos comienzos y autonomía resuelta. El cosmos ampara determinaciones audaces, quebrando la pasividad con un impulso tajante y seguro.\n\nFía tu juicio a tu instinto más que al dictamen ajeno. Enarbola tu soberanía, da el paso inaugural en tus afanes y marca el compás a través de tu entereza.`,

    2: `Una jornada gobernada por la finura psicológica, la escucha serena y el tacto en los vínculos. El triunfo de hoy no se alcanza con imposiciones, sino mediante la mediación, la prudencia y el trato discreto.\n\nConserva tu templanza. Presta atención a lo velado, tiende puentes de entendimiento y permite que los acuerdos cuajen a su debido tiempo.`,

    3: `Una jornada pletórica de inventiva, agudeza verbal y jovialidad comunicativa. Tu palabra goza de elocuencia y simpatía, brindando la coyuntura idónea para compartir proyectos, templar enojos con agudeza y gozar de la vida.\n\nDeja que tu vitalidad ilumine el entorno. Trata con amigos, proyecta iniciativas y permite que tu gracia natural disipe cualquier frialdad.`,

    4: `Una jornada fundada en el juicio sobrio, el método estricto y la disciplina ordenadora. La corriente reclama esmero en el pormenor, lealtad a los compromisos y solidez en el desempeño.\n\nAcomete tus faenas con vocación de artesano. Asentar el orden en tu mundo material y administrativo te reportará serenidad instantánea y certidumbre.`,

    5: `Una jornada electrificada por giros inesperados, dinamismo y ductilidad mental. Los planes inflexibles ceden el paso, instándote a amoldarte con ligereza e ingenio a la mudanza.\n\nGuarda una actitud vivaz ante lo imprevisto. Asume las novedades como cauces de aprendizaje, gobernando el nerviosismo mediante una dirección consciente.`,

    6: `Una jornada inclinada hacia el afecto, la compostura del hogar y la concordia familiar. Tu ánimo se consagra al resguardo de tus seres queridos y al primor de tu refugio privado.\n\nDispensa ternura comprensiva, estimula la concordia y abriga tu morada. Ten presente que la caridad más noble principia por el respeto a tu propia paz.`,

    7: `Una jornada destinada a la soledad fecunda, la indagación abstracta y la intuición serena. El mundo exterior puede tornarse ruidoso; tu mayor baluarte reside en el retiro discreto y la meditación.\n\nHonra tus ansias de recogimiento. Huye de precipitaciones, ahonda en lecturas formativas y encomienda tus dudas al veredicto que madure en el reposo.`,

    8: `Una jornada de firmeza directiva, sentido práctico y miras económicas elevadas. El panorama exige aplomo profesional, juicio lúcido y gobierno austero de tus bienes terrenales.\n\nAsume tu valía sin vacilaciones. Capitanea negociaciones con rectitud y adopta las decisiones procedentes para afianzar tu soberanía material.`,

    9: `Una jornada de conclusiones serenas, indulgencia franca y desasimiento liberador. El influjo es óptimo para despachar asuntos rezagados, desprenderte de lo superfluo y perdonar agravios añejos.\n\nSuelta con nobleza de espíritu. Lo que culminas con paz en esta fecha despeja el terreno para las nuevas auroras que asoman en tu horizonte.`,
  },
};
