// Interpretacoes dos Dons e Talentos Ocultos (Expression - Hidden Talents / High Frequency Gifts)
// Numeros 1 a 9 e Numeros Mestres 11, 22, 33 nos idiomas EN, PT e ES.
// Cada entrada contem 3 paragrafos substanciais separados por \n\n, estilo Carl Jung / Co-Star.

export const EXPRESSION_INTERPRETATIONS: Record<'en' | 'pt' | 'es', Record<number, string>> = {
  en: {
    1: `The vibration of your Expression number confers an innate genius for sovereign invention, strategic audacity, and executive breakthrough. You are equipped with an intellectual battery that refuses to rely on precedents, generating original answers where others see only impasses.\n\nYour operational potency thrives in moments requiring immediate command. While collective opinion stalls in hesitation, your instinct identifies the direct line between intent and execution. You possess a rare psychological stamina that converts solitary initiative into momentum that others naturally rally around.\n\nAt your highest octave, your creative force is luminous and unpossessive. You invent systems, launch enterprises, and pioneer methodologies not to dominate others, but to expand the boundaries of what is possible, leaving behind a clear path of empowerment for everyone who follows.`,

    2: `Your Expression frequency endows you with supreme diplomatic intelligence, atmospheric acuity, and the art of psychological nuance. Your mind operates like a high-precision seismograph, registering unspoken motives, underlying emotional currents, and subtle relational imbalances.\n\nYour gift shines brightly in negotiations, crisis de-escalation, and alliance architecture. You have the uncanny ability to weave harmony among divergent personalities without resorting to force, guiding discussions toward win-win resolutions through quiet patience and empathetic timing.\n\nIn its elevated manifestation, your power is the quiet alchemy that sustains organizations, families, and partnerships. You act as the indispensable glue that turns chaotic groups into cohesive, trusting communities where every voice feels seen and valued.`,

    3: `The vibrational signature of your Expression grants extraordinary communicative mastery, creative alchemy, and infectious charisma. You possess the verbal and aesthetic brilliance to clothe complex emotional truths in metaphors that captivate minds and melt social cynicism.\n\nYour practical genius flourishes in writing, speech, visual design, and cultural innovation. You synthesize concepts with effortless wit, turning dry facts into living stories that make people feel seen, energized, and connected to their own creative pulse.\n\nAt your summit, your creative gift becomes sacred medicine for collective morale. By channeling your sparkling enthusiasm into projects of authentic substance, you dismantle rigid social dogmas and illuminate the sheer wonder of conscious living.`,

    4: `Your Expression frequency grants the extraordinary gift of structural engineering, methodical clarity, and institutional perseverance. You possess a mind capable of taking chaotic, disembodied visions and breaking them down into precise, step-by-step master plans.\n\nYour operational strength is unmatched when it comes to execution, systemization, and risk mitigation. While others burn out through erratic spurts of enthusiasm, your grounded discipline moves with the inexorable power of tectonic plates, ensuring that whatever you build is durable, secure, and solvent.\n\nIn its highest expression, your work is a sacred service to human safety and progress. The foundations you pour, the protocols you establish, and the structures you sustain become the bedrock upon which countless individuals build their livelihoods.`,

    5: `Your Expression number endows you with an electrifying adaptability, linguistic versatility, and catalytic brilliance. You possess an intellectual agility that allows you to master diverse disciplines in record time, instinctively spotting emerging trends and translating avant-garde concepts for the mainstream.\n\nYour operative genius excels in dynamic environments, rapid pivots, marketing, exploration, and media. You are an instinctive networker and storyteller who thrives at the intersection of different cultures and perspectives, connecting disparate ideas to spark revolutionary innovation.\n\nAt your highest vibration, you are a master of purposeful evolution. You teach the collective how to shed stagnant habits without fear, demonstrating that true security lies not in rigid preservation, but in fluid mastery of life’s ever-changing tides.`,

    6: `The frequency of your Expression bestows a supreme talent for healing, aesthetic harmony, and compassionate governance. You possess an instinct for creating sanctuaries of order and warmth, elevating interpersonal environments through refined taste and paternal/maternal benevolence.\n\nYour practical ability is legendary in community stewardship, education, counseling, and restorative justice. People instinctively trust your counsel because it is forged in uncompromising integrity and genuine concern for the long-term well-being of the whole.\n\nAt your most elevated frequency, your operational force transforms every circle you enter. You heal systemic estrangements, mentor rising talent, and anchor ethical standards, proving that boundless empathy and executive competence are one and the same.`,

    7: `Your Expression number equips you with a formidable intellectual laser, forensic discernment, and intuitive problem-solving genius. Your mind cuts through superficial illusions and marketing noise, seeking the underlying mathematical, psychological, or metaphysical laws governing reality.\n\nYour vocational strengths excel in research, specialized science, software architecture, psychoanalysis, and esoteric philosophy. You possess the patience to dwell in deep contemplation for hours, extracting pristine insights from complex oceans of data that overwhelm ordinary thinkers.\n\nIn its highest octave, your intellectual gift serves as an oracle of truth. The theories you formulate, the bugs you diagnose, and the truths you uncover dispel ignorance, providing a bedrock of factual clarity in a confused world.`,

    8: `Your Expression frequency grants commanding executive vision, material alchemy, and financial architecture. You understand how the physical world moves: how capital flows, how organizations scale, and how disparate resources can be organized into self-sustaining engines of prosperity.\n\nYour operative genius thrives in high-stakes environments, organizational leadership, real estate, commerce, and systemic turnarounds. You possess the emotional resilience and decisive nerve required to bear massive responsibilities without wavering under pressure.\n\nAt your highest summit, your mastery over matter becomes an instrument of justice. You build institutions, generate ethical wealth, and empower communities, utilizing your material command to manifest dignified realities for thousands.`,

    9: `The vibration of your Expression bestows expansive humanitarian vision, cultural charisma, and universal artistic synthesis. You possess a consciousness that naturally grasps global perspectives, translating complex human suffering into movements of collective healing and redemption.\n\nYour operational talents shine in diplomacy, philanthropy, international affairs, dramatic arts, and transformative philosophy. You have a magnetic presence that commands respect across diverse social strata, inspiring people to look past parochial divisions and embrace a higher collective destiny.\n\nIn its most luminous octave, your life work is an act of universal stewardship. You release personal attachment to accolades, utilizing your broad influence to awaken generosity, justice, and spiritual solidarity across human society.`,

    11: `Your Expression frequency carries the electric brilliance of the Visionary Medium and Spiritual Innovator. You possess an extraordinary conduit to archetypal knowledge, receiving intuitive breakthroughs and paradigm-shifting concepts as sudden flashes of pure clarity.\n\nYour operative potency excels in creative philosophy, metaphysical instruction, avant-garde arts, and inspirational leadership. You possess an uncanny psychological presence that instantly awakens latent potential in others, compelling them to rise above mundane mediocrity.\n\nAt your highest frequency, you are a living transducer of higher consciousness. You demystify spiritual truths, anchor elevated ethics into modern culture, and ignite creative revolutions that alter the collective worldview.`,

    22: `Your Expression vibrates with the supreme capacity of the Titan Builder, synthesizing visionary idealism with colossal engineering capability. You do not simply imagine a better world; you possess the pragmatic genius to draft the blueprints and coordinate the logistics to build it.\n\nYour practical strength thrives in managing monumental endeavors: multinational infrastructure, regenerative systems, civic networks, and revolutionary technological platforms. You command respect because your ambition is matched by meticulous attention to foundational feasibility.\n\nIn its highest manifestation, your operative genius shapes the physical terrain of civilization. You leave behind enduring institutions, bridges, and systems that will continue to nourish and liberate society long after your time on earth.`,

    33: `Your Expression frequency vibrates with the consummate gift of the Sacred Healer and Master Teacher. You possess an almost miraculous emotional intelligence, capable of consoling the deepest wounds of the human psyche with a single spoken truth or loving gesture.\n\nYour vocational potency excels in restorative education, spiritual mentorship, clinical therapeutics, and humanitarian leadership. You teach by total embodiment of your principles, disarming skepticism through the sheer purity of your benevolence and moral clarity.\n\nAt your highest octave, your life becomes a sanctuary of universal grace. You inspire entire communities to choose reconciliation over retribution, elevating human consciousness toward unconditional compassion and spiritual communion.`,
  },
  pt: {
    1: `A vibração do seu número de Expressão confere um gênio inato para a invenção soberana, ousadia estratégica e liderança pioneira. Você foi dotado de um motor mental que recusa atalhos copiados, gerando soluções originais onde o senso comum enxerga apenas bloqueios e impossibilidades.\n\nSua potência operacional brilha com intensidade máxima em momentos que demandam comando imediato e coragem executiva. Enquanto o coletivo hesita diante do risco, seu instinto traça a rota direta entre a intenção e a ação concreta, inspirando confiança e mobilizando forças ao seu redor.\n\nEm sua oitava mais elevada, sua força criadora é generosa e desapegada da vaidade. Você abre caminhos, funda negócios e inaugura métodos não para impor domínio, mas para expandir os limites do possível, deixando um legado de autonomia para quem vier depois.`,

    2: `Sua frequência de Expressão concede uma inteligência diplomática refinada, sensibilidade ambiental aguda e maestria no trato humano. Sua mente funciona como um sismógrafo de alta precisão, captando nuances não ditas, motivações ocultas e tensões relacionais invisíveis ao observador comum.\n\nSeu dom brilha de forma decisiva na mediação de conflitos, na construção de alianças e no trabalho em equipe. Você possui a habilidade rara de harmonizar vontades divergentes sem recorrer ao autoritarismo, conduzindo impasses rumo ao consenso através da paciência e do tato empático.\n\nEm sua manifestação mais nobre, sua força é a argamassa invisível que sustenta organizações, lares e parcerias duradouras. Você atua como o elo de confiança que transforma grupos fragmentados em comunidades sólidas e acolhedoras.`,

    3: `A assinatura vibracional da sua Expressão concede um domínio magnético da comunicação, talento estético singular e carisma envolvente. Você possui a capacidade nata de traduzir sentimentos complexos em metáforas acessíveis, iluminando conversas e despertando o entusiasmo coletivo.\n\nSeu gênio prático floresce na escrita, oratória, artes visuais, relações públicas e inovação cultural. Você conecta ideias aparentemente distantes com leveza e humor inteligente, transformando o cotidiano em poesia viva e desarmando defesas emocionais com espontaneidade.\n\nNo ápice da sua potência, sua comunicação atua como bálsamo social. Ao direcionar seu brilho verbal e artístico para causas profundas, você desafia o cinismo da época e devolve à sociedade o encanto e a beleza de viver com propósito.`,

    4: `Sua frequência de Expressão outorga a rara vocação para a engenharia de processos, organização metódica e construção duradoura. Sua mente é especialista em receber conceitos caóticos ou abstratos e desdobrá-los em etapas lógicas, seguras e perfeitamente realizáveis.\n\nSua força operacional é inigualável quando o assunto é execução paciente, gestão de riscos e sustentação estrutural. Enquanto outros sucumbem ao imediatismo, sua perseverança avança com a solidez de rocha, garantindo estabilidade e resultados à prova de intempéries.\n\nEm sua expressão mais alta, seu trabalho é um ato de proteção social. Os sistemas que você organiza, as rotinas que estabelece e as fundações que edifica tornam-se o porto seguro sobre o qual inúmeras famílias e projetos prosperam com dignidade.`,

    5: `Seu número de Expressão equipa você com inteligência dinâmica, agilidade linguística e capacidade catalisadora. Sua mente aprende em velocidade exponencial, assimilando novos idiomas, ferramentas tecnológicas e tendências comportamentais com naturalidade desconcertante.\n\nSeu talento operativo prospera em ambientes de rápida transformação, negociações internacionais, marketing inovador e exploração de mercados virgens. Você é um articulador nato que enxerga pontes entre universos distintos, oxigenando ideias antigas e quebrando dogmas engessados.\n\nNa sua frequência superior, você é um mestre da transição consciente. Você ensina as pessoas a perderem o medo da mudança, mostrando que a verdadeira segurança não está na estagnação, mas na capacidade de navegar com fluidez os ventos do imprevisto.`,

    6: `A frequência da sua Expressão manifesta um dom supremo para o acolhimento, restauração estética e liderança ética. Você possui o olhar clínico para diagnosticar fragilidades humanas e carências comunitárias, restaurando a dignidade e a beleza onde quer que atue.\n\nSua vocação prática se destaca na educação, na consultoria familiar, no design harmonizador e na gestão de equipes baseada no respeito. As pessoas confiam naturalmente nas suas diretrizes porque percebem que suas decisões priorizam o bem-estar duradouro de todos os envolvidos.\n\nEm sua manifestação luminosa, sua energia repara o tecido social. Você atua como curador de desavenças, mentor generoso e guardião da ética, provando que a verdadeira autoridade nasce do amor responsável e do serviço altruísta.`,

    7: `Seu número de Expressão concede um discernimento intelectual cirúrgico, rigor investigativo e intuição refinada. Sua mente ignora a superficialidade do senso comum e penetra nas causas raízes dos fenômenos, decifrando as engrenagens ocultas da ciência e do psiquismo humano.\n\nSeus talentos operacionais alcançam a excelência na pesquisa científica, programação avançada, psicanálise, filosofia e estratégia de inteligência. Você possui a capacidade de sustentar concentração profunda por longos períodos, extraindo sínteses luminosas de labirintos complexos de informação.\n\nNo ápice do seu dom, sua inteligência serve como farol de lucidez. As análises que você elabora e os princípios que decodifica dissipam a desinformação, oferecendo um solo firme de coerência e verdade para orientar decisões cruciais.`,

    8: `Sua Expressão outorga comando estratégico, visão de negócios monumental e maestria no gerenciamento de recursos. Você compreende com naturalidade as regras do mundo material: a geração de riqueza, a alavancagem de capitais e a orquestração de grandes engrenagens operacionais.\n\nSua competência executiva brilha em momentos de pressão extrema, reestruturações corporativas, gestão patrimonial e investimentos audaciosos. Você possui nervos de aço e senso de responsabilidade para tomar decisões de alto impacto sem se deixar abalar por ruídos circunstanciais.\n\nEm sua oitava suprema, sua capacidade materializadora se torna ferramenta de empoderamento humano. Você ergue empreendimentos que geram prosperidade limpa, abrem postos de trabalho e distribuem valor, exercendo o poder material com justiça e nobreza de espírito.`,

    9: `A vibração da sua Expressão confere visão humanitária abrangente, carisma universal e talento artístico sintetizador. Sua consciência opera em escala planetária, compreendendo as dores do mundo e formulando narrativas de esperança e reintegração coletiva.\n\nSeus dons brilham intensamente na diplomacia, na defesa dos direitos humanos, nas artes dramáticas, na filantropia e na liderança espiritual. Sua presença impõe reverência natural porque transcende partidarismos mesquinhos, tocando a essência do que há de mais humano em cada indivíduo.\n\nEm seu grau mais sublime, sua obra é uma oferenda ao progresso moral da Terra. Você coloca seus consideráveis talentos a serviço da paz e da redenção, inspirando homens e mulheres a superarem preconceitos e viverem como irmãos em um lar comum.`,

    11: `Sua frequência de Expressão carrega a voltagem genial do Visionário Transcendente e Inovador Espiritual. Você possui uma antena psíquica permanentemente sintonizada com o inconsciente coletivo, captando conceitos de vanguarda e diretrizes evolutivas anos antes do seu tempo.\n\nSua força prática se revela nas artes transformadoras, na oratória visionária, na psicologia profunda e nas ciências de fronteira. Você tem a capacidade magnética de elevar a frequência energética dos ambientes e despertar o potencial adormecido nas pessoas apenas com sua presença lúcida.\n\nNo ápice da sua vibração, você atua como um tradutor da consciência cósmica. Você desmistifica conceitos espirituais, propõe novos paradigmas éticos e lidera movimentos que devolvem o sagrado ao cotidiano da sociedade moderna.`,

    22: `Sua Expressão vibra com a capacidade colossal do Construtor Universal, fundindo grandes ideais civilizatórios ao mais apurado rigor logístico. Você não é apenas um sonhador; você detém a tecnologia mental necessária para transformar sonhos monumentais em realidade tangível.\n\nSua competência operacional é requisitada em projetos de escala global: infraestruturas ecológicas, sistemas educacionais modernos e inovações que remodelam indústrias inteiras. Sua liderança é inquestionável porque combina ambição grandiosa com precisão milimétrica de execução.\n\nEm sua manifestação mais elevada, sua obra redefine a paisagem do mundo. Você deixa para trás obras cívicas, instituições e modelos de sustentabilidade que beneficiarão a humanidade por muitos séculos.`,

    33: `Sua frequência de Expressão vibra com o dom supremo do Mestre Consolador e Curador de Almas. Você possui uma sensibilidade curativa capaz de desarmar o sofrimento psíquico mais arraigado através de palavras simples, amor genuíno e presença compassiva.\n\nSua vocação floresce na orientação humanitária, na saúde integrativa, na liderança espiritual e no socorro a populações marginalizadas. Você ensina pela transparência dos seus atos, demonstrando que a pureza de intenção e a lealdade ao bem são as forças mais invencíveis do universo.\n\nNo ápice do seu poder, sua vida torna-se um refúgio para os aflitos. Você estabelece correntes de solidariedade inabaláveis, elevando a vibração moral da sociedade e inspirando o perdão sincero onde antes reinava a divisão.`,
  },
  es: {
    1: `La vibración de tu número de Expresión otorga un talento innato para la invención soberana, la audacia estratégica y el liderazgo fundador. Cuentas con un motor psíquico que rechaza las fórmulas trilladas, concibiendo soluciones originales donde el criterio común solo tropieza con barreras.\n\nTu potencia operativa alcanza su plenitud en circunstancias que reclaman mando inmediato y serenidad ante el riesgo. Mientras la colectividad vacila, tu instinto traza la ruta recta entre el propósito y la ejecución palpable, contagiando seguridad y movilizando recursos a tu alrededor.\n\nEn tu octava más alta, tu fuerza creadora es magnánima y ajena a la vanidad. Abres surcos, fundas iniciativas y formulas métodos no para imponer vasallajes, sino para dilatar los confines de lo realizable, dejando un sendero despejado para quienes te sucedan.`,

    2: `Tu frecuencia de Expresión te confiere una inteligencia diplomática prodigiosa, perspicacia ambiental y magisterio en los vínculos. Tu mente se comporta como un sismógrafo de alta precisión, descifrando inflexiones sutiles, intenciones veladas y desequilibrios relacionales inadvertidos para el común.\n\nTu don se corona en la conciliación de conflictos, el tejido de pactos fecundos y la cohesión de equipos. Posees la destreza excepcional de aunar voluntades dispares sin acudir a la coacción, conduciendo los desacuerdos hacia la concordia mediante el tacto paciente y la empatía oportuna.\n\nEn su manifestación más noble, tu poder es la argamasa invisible que cohesiona familias, empresas y alianzas duraderas. Obras como el eslabón sagrado que transforma grupos fragmentados en comunidades sólidas donde cada voz halla acogida y dignidad.`,

    3: `La impronta vibratoria de tu Expresión confiere una maestría deslumbrante en la comunicación, sensibilidad estética y carisma magnético. Posees la facultad innata de verter emociones complejas en imágenes nítidas, encendiendo el entusiasmo de quienes te escuchan y aliviando el peso de la vida cotidiana.\n\nTu genio práctico resplandece en las letras, la oratoria, las artes visuales y la dinamización cultural. Enlazas conceptos distantes con ingenio chispeante, convirtiendo lo árido en relato vivo y desarmando la apatía mediante la gracia y la espontaneidad creadora.\n\nEn la cima de tu potencial, tu palabra opera como medicina para el ánimo social. Al consagrar tu brillo a causas sustantivas, desbaratas el cinismo de la época y devuelves a la convivencia humana la alegría y el asombro por la belleza del existir.`,

    4: `Tu frecuencia de Expresión te dota de una aptitud magistral para la ingeniería de métodos, la templanza operativa y la construcción perdurable. Tu entendimiento destaca al tomar visiones etéreas y estructurarlas en procedimientos rigurosos, seguros y enteramente viables.\n\nTu firmeza operativa es insuperable en la ejecución meticulosa, el cálculo preventivo y la consolidación de sistemas. Mientras otros flaquean por la prisa, tu constancia avanza con la solidez de la roca, asegurando resultados invulnerables al desgaste y al azar.\n\nEn tu expresión más elevada, tu labor es un escudo para la sociedad. Las normas que estableces, los protocolos que afinas y las estructuras que levantas constituyen el baluarte seguro donde innumerables personas prosperan con tranquilidad.`,

    5: `Tu número de Expresión te brinda una inteligencia vertiginosa, ductilidad verbal y un magnetismo transformador. Tu mente asimila nuevos saberes a un ritmo prodigioso, dominando idiomas, adelantos tecnológicos y corrientes culturales con asombrosa soltura.\n\nTu talento práctico florece en escenarios de rápida evolución, negociaciones cosmopolitas, comunicación de vanguardia y apertura de nuevos senderos. Eres un conector nato que tienda puentes entre realidades divergentes, refrescando criterios añejos y demoliendo dogmas obsoletos.\n\nEn tu frecuencia superior, eres un maestro de la metamorfosis consciente. Desvaneces en otros el miedo a lo imprevisto, acreditando que la auténtica estabilidad no reside en el inmovilismo, sino en el dominio sereno de los vientos del cambio.`,

    6: `La frecuencia de tu Expresión revela un don sublime para la restauración afectiva, la armonía espacial y la dirección compasiva. Cuentas con una mirada aguda para detectar fisuras emocionales y necesidades ajenas, devolviendo el decoro y la serenidad allá donde intervienes.\n\nTu vocación se distingue en el magisterio, la mediación ética, el interiorismo sanador y la conducción generosa de comunidades. Quienes te rodean confían en tu criterio porque palpan que tus resoluciones buscan la salud integral y perdurable de todos.\n\nEn su fruto más luminoso, tu energía recompone los lazos humanos. Actúas como bálsamo ante las divisiones, formador desinteresado y custodio de la rectitud, demostrando que el verdadero liderazgo se funda en la ternura lúcida y el servicio abnegado.`,

    7: `Tu número de Expresión te provee de un bisturí intelectual implacable, escrúpulo analítico y clarividencia intuitiva. Tu mente desestima la superficialidad para consagrarse a las causas primarias, desentrañando los códigos ocultos de la materia, la mente y el misterio universal.\n\nTu potencial alcanza la maestría en la investigación de punta, las ciencias de la computación, el psicoanálisis, la filosofía y la prospección estratégica. Posees la disciplina del silencio concentrado, extrayendo certezas cristalinas de los más intrincados dédalos conceptuales.\n\nEn la cumbre de tu don, tu lucidez es un faro inextinguible. Las explicaciones que formulas y los enigmas que resuelves dispersan la ignorancia, dotando a la colectividad de un suelo firme de sensatez y verdad para encarar dilemas mayúsculos.`,

    8: `Tu Expresión te inviste de un porte soberano, visión económica titánica y maestría en la administración de voluntades y recursos. Entiendes las leyes del mundo práctico: el flujo de la riqueza, la estructuración institucional y la conjunción de voluntades para consumar metas grandiosas.\n\nTu pericia directiva brilla en coyunturas de máxima exigencia, arbitraje financiero, reactivación de entidades y maniobras complejas. Posees temple de acero y entereza ética para asumir responsabilidades descomunales sin titubear ante las borrascas del entorno.\n\nEn tu grado supremo, tu capacidad materializadora es un baluarte de redención social. Edificas emporios limpios, fomentas fuentes de trabajo y distribuyes prosperidad, administrando el poder terrenal con estricta equidad y dignidad de espíritu.`,

    9: `La vibración de tu Expresión concede una visión humanitaria sin fronteras, resonancia ecuménica y genialidad artística integradora. Tu mente vibra en concordancia con el destino planetario, traduciendo el dolor de la época en epopeyas de esperanza y despertar colectivo.\n\nTu talento florece en la carrera diplomática, la protección de los desvalidos, las bellas artes, la filantropía y la guía espiritual. Tu figura despierta un acatamiento reverente porque trasciende banderías mezquinas, apelando a lo más sagrado que late en el pecho de cada criatura.\n\nEn su cumbre bienaventurada, tu obra es una ofrenda a la hermandad del orbe. Pones tus insignes dones a disposición de la conciliación y la piedad, exhortando a la humanidad a desterrar prejuicios y reconocerse como una sola familia bajo el firmamento.`,

    11: `Tu frecuencia de Expresión late con el fulgor visionario del Inspirador Espiritual e Innovador Paradigmático. Tu psique actúa como una terminal enlazada con las reservas de la sabiduría arquetípica, captando visiones sublimes y rumbos evolutivos antes de que asomen al mundo.\n\nTu vigor práctico resplandece en las artes transformadoras, la docencia iniciática, la psicología de lo profundo y las ideas de vanguardia. Ejerces un influjo magnético que remueve la somnolencia ajena y enciende las brasas del talento dormido con tu sola rectitud.\n\nEn tu mayor plenitud, eres un heraldo de la verdad superior. Despojas de sombras los misterios del alma, propones éticas renovadas y capitaneas corrientes que reconcilian la modernidad con la dimensión sagrada de la vida.`,

    22: `Tu Expresión vibra con la potencia cósmica del Arquitecto Universal, enlazando aspiraciones civilizatorias con la más inflexible destreza logística. No eres un mero forjador de utopías; posees el rigor mental indispensable para verter sueños colosales en estructuras vivas.\n\nTu genio rector se evidencia en iniciativas de alcance continental: infraestructuras sostenibles, reformas orgánicas y modelos que transforman sectores enteros. Tu autoridad es indiscutible porque acompasa la grandeza del propósito con una escrupulosidad técnica perfecta.\n\nEn su máxima expresión, tu legado esculpe el destino de las sociedades. Dejas tras de ti monumentos cívicos, instituciones tutelares y esquemas de convivencia que ampararán a la humanidad durante largas eras.`,

    33: `Tu frecuencia de Expresión se corona con el ministerio supremo del Consolador de Almas y Maestro de Compasión. Eres depositario de una sabiduría curativa que desvanece las zozobras más enquistadas a través de la rectitud, la ternura incondicional y el bálsamo de tu presencia.\n\nTu vocación se consagra al auxilio de los quebrantados, la medicina del espíritu, el cuidado compasivo y la redención de almas extraviadas. Enseñas con la verdad transparente de tu testimonio, confirmando que la nobleza del alma y la benevolencia son las potestades más altas del universo.\n\nEn el cenit de tu gracia, tu existencia se erige en asilo para los que sufren. Desatas mareas de solidaridad viva, purificas la conciencia de tu tiempo e inspiras el perdón más heroico allá donde reinaba el encono.`,
  },
};
