// Interpretacoes Profundas da Personalidade Exterior (Personality / Social Persona)
// Numeros 1 a 9 e Numeros Mestres 11, 22, 33 nos idiomas EN, PT e ES.
// Cada entrada contem 3 paragrafos substanciais separados por \n\n, estilo Carl Jung / Co-Star.

import { interpolateFirstName } from './utils';

export const PERSONALITY_INTERPRETATIONS: Record<'en' | 'pt' | 'es', Record<number, string>> = {
  en: {
    1: `To the outer world, {name}, you project an undeniable aura of pioneering self-reliance, bold initiative, and dignified command. People naturally step aside to let you lead, sensing that you possess the courage to enter unfamiliar territory and set the pace for others.\n\nYour social presence, {name}, is defined by crisp directness and purposeful momentum. You do not loiter in hesitation or hide behind diplomatic ambiguity; your communication is straightforward, energetic, and unapologetically authentic, which commands immediate attention in any room.\n\nYour challenge lies in softening the sharp edge of independence; true authority inspires willing allegiance rather than distant reverence. When you temper your commanding aura with approachable warmth, {name}, your public leadership becomes truly magnetic.`,

    2: `Your outward presence, {name}, radiates calming grace, refined tact, and approachable gentleness. Others perceive you as a peaceful harbor, instinctively turning to you in moments of interpersonal conflict or delicate negotiations.\n\nSocially, {name}, you are a master of active listening and atmospheric awareness. You notice the quietest person at the table, smooth over social blunders with discreet elegance, and create an ambiance where people feel emotionally safe to drop their pretenses.\n\nBe mindful not to let your gracious diplomacy be mistaken for passivity. When your gentle receptivity is grounded in firm self-respect and clear personal convictions, {name}, your diplomatic aura becomes an unstoppable force of harmony.`,

    3: `You enter any room like a breath of fresh air, {name}, projecting exuberance, wit, and magnetic verbal charm. People are drawn to your conversational flair and your capacity to uplift the collective mood with spontaneous levity and creative insight.\n\nYour public persona, {name}, is expressive, stylish, and engaging. You have an instinct for storytelling, clever phrasing, and contagious enthusiasm, turning ordinary social gatherings into memorable celebrations of human connection.\n\nYour social gift is profound, {name}, provided you balance sparkling sociability with substance. Ensure your genuine intellectual and emotional depth is never overshadowed by the performance of entertainment, allowing people to know the real thinker behind the smile.`,

    4: `Your social demeanor, {name}, is the epitome of dependability, grounded calm, and methodical integrity. Others instantly trust you with responsibilities, perceiving an unshakeable bedrock of discipline, punctuality, and realistic counsel.\n\nYou convey an aura of dignified competence and quiet strength, {name}. You do not boast or exaggerate; your promises are treated like solemn contracts, and your presence brings immediate stability and reassurance to turbulent environments.\n\nTake care that your aura of solemn duty does not become an impenetrable fortress. Welcoming spontaneous warmth and open-minded flexibility, {name}, enriches the immense respect and trust you already command from society.`,

    5: `You project an electrifying aura of versatility, {name}, progressive charm, and thirst for adventure. People sense an unpredictable, worldly spark in you, instinctively perceiving that you belong to the open horizons rather than narrow conventions.\n\nYour social energy is dynamic, quick-witted, and refreshingly candid, {name}. You move effortlessly between diverse social circles, inspiring people to question stale dogmas, try new experiences, and look at the world through an expansive, modern lens.\n\nYour presence is exhilarating, {name}, but you gain maximum respect when your thirst for freedom is anchored in deliberate follow-through. When versatility is matched by reliability, your charisma becomes an irresistible agent of positive change.`,

    6: `Your aura emanates warm benevolence, {name}, domestic harmony, and genuine protective grace. Others feel immediately embraced and emotionally safe in your perimeter, recognizing a born counselor, hospitable host, and mediator of disputes.\n\nYou project an image of aesthetic refinement, moral stability, and compassionate responsibility, {name}. Whether in your home or your workplace, you cultivate spaces of comfort, beauty, and mutual care where people feel deeply honored and understood.\n\nBeware only of projecting an urge to fix or supervise everyone around you. Unconditional acceptance and gentle encouragement, {name}, are the most magnetic crowns of your nurturing presence, turning your care into pure inspiration.`,

    7: `You project an enigmatic, dignified presence, {name}, marked by intellectual elegance and quiet depth. Others perceive an aristocratic reserve about you, sensing that you observe far more than you reveal and walk with an inner philosopher.\n\nIn social situations, {name}, you speak only when you have something meaningful to say. Your demeanor is composed, discerning, and analytical; you avoid trivial gossip, effortlessly steering conversations toward deeper intellectual or existential territory.\n\nYour contemplative mystique is compelling, {name}; simply ensure that healthy introspective solitude does not drift into unintentional aloofness. Sharing your warm humanity alongside your vast intellect bridges the distance between your brilliance and the world.`,

    8: `Your aura projects executive authority, {name}, prosperous competence, and unhesitating personal power. People instinctively treat you as an achiever capable of navigating complex material dynamics, leading organizations, and making decisive high-stakes calls.\n\nYou carry yourself with natural gravitas and imposing confidence, {name}. You appreciate quality, efficiency, and professional excellence, inspiring those around you to elevate their performance and pursue ambitious standards of achievement.\n\nYour presence commands instant respect, {name}; soften that force with genuine humility and accessible empathy. When you use your power to mentor and empower others, deference transforms into lifelong loyalty and shared triumph.`,

    9: `Your public impression, {name}, is that of a cultured, worldly, and deeply generous benefactor. Others sense in you a universal perspective that transcends local prejudices, carrying the dignified grace of someone who has lived many lifetimes.\n\nYou project an aura of noble tolerance, artistic breadth, and broad-minded compassion, {name}. People from all walks of life feel accepted in your presence, sensing that you judge character by moral substance rather than social status.\n\nYour charismatic nobility is vast, {name}; remain personally accessible so that your universal ideals translate into warm individual fellowship. Grounding your humanitarian vision in daily kindness makes your public presence an enduring blessing.`,

    11: `Your presence radiates a subtle, hypnotic spiritual magnetism and visionary sensitivity, {name}. Others often feel an uncanny sense of being seen to the core when talking to you, perceiving an otherworldly charisma that defies ordinary logic.\n\nYou carry an aura of electric inspiration and psychic intensity, {name}. Your words often carry prophetic weight, sparking sudden epiphanies and emotional breakthroughs in people who cross your path, even during brief interactions.\n\nGround your electrifying energetic voltage in tranquil presence and humble simplicity. When your transcendent intuition is delivered with calm, grounded practicality, {name}, your guidance brings reassuring clarity rather than overwhelming intensity.`,

    22: `You project the gravitas and expansive capability of a master architect, {name}, who shapes institutions and communities. People immediately sense that small talk does not suit you; you convey the quiet confidence of someone born to materialize monumental visions.\n\nYour demeanor combines commanding scale with meticulous pragmatic realism, {name}. You speak with the authority of someone who understands how the world works, naturally drawing collaborators and leaders who wish to build enduring structures under your direction.\n\nPair your immense visionary presence with approachable patience, {name}. Giving others the time and encouragement to grow into the grand horizons you effortlessly perceive ensures that your monument is supported by dedicated, inspired allies.`,

    33: `Your social presence emanates deep spiritual solace, {name}, radiant empathy, and selfless benevolence. You walk with the quiet grace of a master teacher whose very gaze calms anxiety, disarms hostility, and reminds people of human dignity.\n\nYour aura feels like a warm sanctuary in a chaotic world, {name}. Strangers often feel an irresistible urge to confide their deepest sorrows in you, instinctively recognizing a spirit capable of holding their vulnerability with sacred reverence.\n\nYour healing aura is a blessing to all, {name}; preserve your energetic reservoir through sacred boundaries so your radiant light remains unextinguished, continuing to console and uplift humanity for decades to come.`,
  },
  pt: {
    1: `Para o mundo exterior, você projeta uma presença magnética de pioneirismo, firmeza inabalável e liderança nata. As pessoas naturalmente abrem caminho para suas iniciativas, pressentindo que você possui coragem de sobra para desbravar cenários incertos e ditar o próprio ritmo.\n\nSua persona pública é marcada pela clareza assertiva e pela agilidade executiva. Você não se perde em rodeios ou meias-palavras; sua comunicação é direta, vigorosa e destemida, transmitindo a confiança necessária para que outros se sintam seguros ao seguir sua direção.\n\nSeu desafio social é suavizar o tom de autossuficiência; a liderança mais nobre atrai cooperação voluntária e não apenas respeito distante. Ao aliar sua firmeza a uma postura calorosa e acolhedora, seu carisma público torna-se verdadeiramente inspirador.`,

    2: `Sua presença transmite serenidade polida, diplomacia refinada e escuta atenta. Os outros o enxergam como um porto seguro de moderação e equilíbrio, recorrendo a você de forma espontânea para mediar conflitos, dissolver tensões relacionais ou encontrar um conselho apaziguador.\n\nSocialmente, você é um mestre da empatia sutil e da etiqueta emocional. Você percebe quem está desconfortável em um grupo, desvia conversas de temas hostis com elegância e cria um ambiente onde todos se sentem ouvidos, validados e respeitados em sua individualidade.\n\nCuide para que sua gentileza natural não seja confundida com fraqueza ou indecisão. Quando sua sensibilidade se ancora em princípios firmes e autoconfiança serena, sua diplomacia se consagra como uma força invencível de concórdia.`,

    3: `Você chega a qualquer ambiente irradiando leveza, carisma comunicativo e inteligência vibrante. As pessoas são cativadas pela sua capacidade de enriquecer conversas, quebrar o gelo com elegância e elevar o ânimo do grupo com espontaneidade e bom humor.\n\nSua imagem pública é elegante, expressiva e envolvente. Você possui o dom natural das narrativas bem contadas e da palavra precisa, transformando encontros ordinários em momentos festivos e inspiradores que marcam a memória de quem convive com você.\n\nSeu dom social é poderoso, desde que você una seu brilho verbal ao compromisso sincero com a verdade. Assegure que sua profundidade emocional e maturidade sejam igualmente percebidas, mostrando a sabedoria que existe por trás do seu sorriso.`,

    4: `Sua postura pública transmite solidez exemplar, confiabilidade inabalável e serenidade pragmática. Os outros sentem que podem lhe confiar as responsabilidades mais decisivas, percebendo um compromisso inquebrantável com a palavra dada, com a ordem e com o trabalho bem feito.\n\nVocê projeta uma imagem de competência discreta e estabilidade à prova de intempéries. Você não precisa se vangloriar; seus resultados falam por si mesmos, e sua presença transmite uma sensação imediata de alívio e segurança em momentos de crise organizacional.\n\nApenas evite parecer excessivamente austero ou intransigente. Permitir-se pequenos toques de flexibilidade, humor e espontaneidade amplia ainda mais a imensa reverência e admiração que a sociedade já nutre por você.`,

    5: `Você projeta uma aura instigante de liberdade, dinamismo cosmopolita e fascínio pelo novo. As pessoas notam de imediato seu espírito inquieto e avesso à mesmice, percebendo que sua mente navega sempre um passo à frente das convenções tradicionais.\n\nSua energia pública é rápida, espirituosa e arejada. Você transita com naturalidade desconcertante entre os mais variados grupos sociais, inspirando as pessoas a desafiarem preconceitos, abraçarem novas ideias e adotarem uma perspectiva moderna e aberta sobre o mundo.\n\nSua presença é contagiante e moderna; seu maior trunfo consiste em aliar essa agilidade ao compromisso consistente com a palavra dada. Quando sua versatilidade caminha de mãos dadas com a lealdade, sua influência se torna um motor irresistível de renovação.`,

    6: `Sua imagem pública transparece acolhimento maternal/paternal, harmonia e generosidade protetora. Os outros se sentem confortáveis na sua presença, identificando em você uma figura de concórdia, bom gosto estético e cuidado genuíno pelo bem-estar e dignidade alheia.\n\nVocê projeta uma postura de equilíbrio moral, bom gosto e acolhimento caloroso. Seja em casa ou no trabalho, você se empenha em organizar ambientes agradáveis e harmoniosos, onde o diálogo flui com respeito mútuo e onde ninguém se sente desamparado.\n\nCuidado apenas para não assumir um tom condescendente ou querer gerenciar os passos de todos ao seu redor. A aceitação incondicional e o estímulo à autonomia são os maiores tesouros da sua presença, transformando seu zelo em pura fonte de paz.`,

    7: `Sua presença é marcada por uma distinção enigmática, elegância reflexiva e nobreza silenciosa. O mundo o percebe como alguém que observa muito mais do que fala, dotado de um olhar clínico e penetrante que enxerga através das aparências ordinárias.\n\nEm sociedade, você evita conversas banais e opiniões fáceis. Sua postura é reservada, nobre e analítica; quando você escolhe falar, suas colocações trazem um peso de autoridade e erudição que silencia debates superficiais e conduz a conversa para a essência dos fatos.\n\nSeu ar de filósofo ou sábio é fascinante; lembre-se apenas de demonstrar afeto acessível com aqueles que o admiram. Ao abrir espaço para a troca emocional espontânea, sua vasta sabedoria deixa de ser distante e passa a tocar o coração das pessoas.`,

    8: `Você transmite autoridade executiva, competência irrefutável e magnetismo de prosperidade material. Os outros o identificam instantaneamente como alguém talhado para lidar com grandes decisões, gerenciar recursos vultosos e gerar resultados práticos de alto impacto.\n\nSua compostura é imponente e exala determinação. Você preza a eficiência, o mérito e a pontualidade, inspirando seus colaboradores e parceiros a superarem a mediocridade e alcançarem novos patamares de disciplina e realização profissional.\n\nSua presença impõe respeito natural; tempere essa força com calor humano e generosidade sincera. Ao utilizar sua influência executiva para impulsionar e mentorar os que estão ao seu lado, a reverência alheia se transforma em lealdade incondicional e admiração eterna.`,

    9: `Sua impressão pública é a de um cidadão do mundo, culto, compassivo e generoso. As pessoas percebem em você uma visão abrangente que ignora mesquinharias provincianas, portando a serenidade digna de quem compreende a alma humana em suas dores e grandezas.\n\nVocê projeta uma aura de tolerância ética, sofisticação humanista e compaixão universal. Qualquer pessoa, independentemente de sua classe social ou origem, sente-se acolhida e respeitada diante de você, reconhecendo um coração desprovido de preconceitos.\n\nSua nobreza moral comove e atrai admiração; mantenha a proximidade cotidiana no trato com cada indivíduo para que seu idealismo ecumênico se traduza em amizade calorosa e apoio concreto no dia a dia.`,

    11: `Sua persona irradia um magnetismo intuitivo sutil, quase hipnótico, e uma sensibilidade visionária fora do comum. Em sua presença, as pessoas sentem que estão sendo compreendidas no âmago da alma, despertando confidências espontâneas e reflexões existenciais.\n\nSua aura pulsa com uma voltagem de eletricidade e inspiração profética. Suas observações casuais frequentemente carregam o peso de revelações transformadoras, quebrando bloqueios emocionais e despertando horizontes superiores em quem cruza seu caminho.\n\nAncore essa vibração elevada em simplicidade e serenidade aterrada. Ao expressar suas intuições extraordinárias com modéstia, paciência e linguagem clara, sua presença age como um farol seguro e apaziguador para mentes desassossegadas.`,

    22: `Você projeta a autoridade serena e gigantesca de quem veio erguer monumentos e estruturar sistemas duradouros para a humanidade. O mundo nota de imediato que conversas fúteis não lhe pertencem; você exala a força pragmática de quem pensa em escala e concretiza o impossível.\n\nSua postura mescla visão estratégica continental a uma atenção minuciosa aos detalhes práticos de execução. As pessoas sentem firmeza irrestrita em suas propostas, sentindo-se motivadas a se unir a grandes projetos sob a sua liderança competente e serena.\n\nUna sua visão monumental à paciência pedagógica com os limites alheios. Ao conceder tempo para que sua equipe assimile e acompanhe seus planos audaciosos, sua presença construtora se consolida com harmonia e sustentabilidade coletiva.`,

    33: `Sua aura pública irradia alívio emocional, sabedoria compassiva e uma bondade desinteressada que acalma corações aflitos. Você caminha com a postura digna de um mestre espiritual cujo contato direto desfaz ansiedades, reconcilia conflitos e recorda o valor intrínseco de cada ser.\n\nSua presença é um refúgio acolhedor em meio à dureza do mundo. As pessoas sentem uma vontade espontânea de desabafar com você suas dores mais íntimas, sentindo que diante do seu olhar não há julgamento, apenas respeito e consolo verdadeiro.\n\nSua energia curadora é uma dádiva coletiva; preserve sua saúde e seu descanso com limites prudentes para que seu fogo sagrado permaneça aceso, continuando a elevar a dignidade humana onde quer que você esteja.`,
  },
  es: {
    1: `Ante el mundo, proyectas un aura innegable de liderazgo pionero, autonomía digna e iniciativa audaz. La gente te abre paso de forma natural, intuyendo que posees el coraje de asumir riesgos y marcar el rumbo.\n\nTu presencia pública se define por la resolución enérgica y la celeridad ejecutiva. No te detienes en circunloquios; tu comunicación es limpia, tajante y desprovista de fingimiento, infundiendo certidumbre en quienes confían en tu juicio.\n\nTu desafío consiste en templar la autosuficiencia; la verdadera autoridad inspira compromiso voluntario y no solo acatamiento respetuoso. Al acompasar tu brío con un trato cercano, tu liderazgo social se torna profundamente magnético.`,

    2: `Tu presencia social destila serenidad diplomática, trato cortés y escucha profunda. Los demás te perciben como un remanso de paz, acudiendo a ti espontáneamente para apaciguar controversias, allanar desavenencias o hallar sosiego en medio de la agitación.\n\nEn lo social, descuellas por tu tacto empático y tu finura relacional. Adviertes al instante el desconcierto ajeno, soslayas fricciones con delicadeza y generas una atmósfera de confianza donde todos se sienten reconocidos y a salvo.\n\nEvita que tu bondad innata sea leída como debilidad o pasividad. Cuando tu suavidad se cimienta en una firme autoestima y principios innegociables, tu diplomacia se yergue como un pilar imbatible de concordia.`,

    3: `Entras en cualquier entorno irradiando ingenio, carisma espontáneo y entusiasmo comunicativo. Los demás se sienten cautivados por tu elocuencia, tu gracia verbal y tu facultad de disipar la pesadumbre con una alegría contagiosa y oportuna.\n\nTu imagen pública es brillante, refinada y vivaz. Posees el don del relato memorable y el decir acertado, convirtiendo las ocasiones comunes en celebraciones enriquecedoras de la calidez humana.\n\nTu don relacional es extraordinario; acompáñalo de coherencia y hondura moral. Asegura que tu peso intelectual y tu madurez emocional sean igualmente palpables, mostrando la sabiduría reflexiva que alumbra tu mirada.`,

    4: `Tu imagen pública es sinónimo de formalidad, disciplina a prueba de fuego y juicio sensato. La gente deposita en ti responsabilidades cruciales, confiando ciegamente en tu puntualidad, tu ética intachable y tu constancia inquebrantable.\n\nTransmites un porte de sobria competencia y solidez invulnerable. Descartas la jactancia; tu ejecutoria habla por ti, infundiendo un alivio instantáneo ante crisis o desórdenes organizativos.\n\nEvita mostrarte excesivamente severo o inaccesible. Permitirte licencias de flexibilidad y calidez enriquecerá la profunda admiración y el respeto reverente que la sociedad ya te rinde.`,

    5: `Proyectas una presencia electrizante, libre y dotada de moderno dinamismo. Quienes te rodean perciben tu aversión a la monotonía y tu mente abierta, considerándote un espíritu cosmopolita, ágil y vanguardista.\n\nTu vigor social es veloz, agudo y desinhibido. Te desenvuelves con maestría en los más diversos estratos, exhortando a la gente a derribar prejuicios, incorporar saberes inéditos y asomarse al mundo con mirada despejada.\n\nTu vitalidad resulta fascinante; canaliza esa versatilidad en lealtad a tus compromisos más nobles. Cuando la agilidad se une a la seriedad en la palabra dada, tu magnetismo se convierte en un ariete invencible de progreso.`,

    6: `Tu porte exterior emana calidez protectora, armonía y vocación de servicio. La gente se siente arropada a tu lado, reconociendo en ti a un protector leal, amante de la concordia, la belleza y la dignidad humana.\n\nReflejas una compostura de equilibrio ético, elegancia serena y acogida generosa. Tanto en tu hogar como en el entorno laboral, procuras crear ámbitos acogedores donde la convivencia se desenvuelva con respeto y rectitud.\n\nNo caigas en la tentación de fiscalizar la vida ajena o pretender resolver todas las zozobras. El respeto a la autonomía del prójimo es el mayor blasón de tu ternura, trocando tu protección en una fuente de paz duradera.`,

    7: `Tu presencia se distingue por una reserva aristocrática, elegancia reflexiva y profundidad intelectual. El mundo intuye que analizas la realidad con bisturí agudo, guardando tus tesoros interiores para momentos selectos de verdadera comunión mental.\n\nEn público desestimas la conversación banal y las disputas pedestres. Tu estampa es sosegada, sabia y juiciosa; cuando tomas la palabra, tus apreciaciones portan una erudición serena que reconduce los diálogos hacia lo esencial.\n\nTu halo misterioso resulta magnético; mantén puentes cálidos con quienes te valoran para no parecer distante en tus relaciones cercanas. Al manifestar afecto accesible, tu profundo saber deja de intimidar para reconfortar el espíritu ajeno.`,

    8: `Exhalas liderazgo ejecutivo, seguridad material y una firmeza decisoria que impone respeto inmediato. La gente te reconoce como alguien dotado para orquestar grandes metas, superar borrascas y materializar riqueza tangible de alto impacto.\n\nTu presencia es mayestática y rezuma aplomo. Valoras la diligencia, el decoro y la eficiencia, exhortando a colaboradores y pares a repudiar la tibieza para abrazar una disciplina constructiva y perdurable.\n\nTu fuerza es admirada; combínala con empatía sincera y magnanimidad. Al emplear tu rango directivo para impulsar el florecimiento de los tuyos, el acatamiento reverente deviene en adhesión voluntaria e incondicional.`,

    9: `Tu estampa pública es la de un humanista noble, sabio y desprendido. Quienes te conocen perciben una mirada panorámica que no se detiene en rivalidades banales, reflejando la serenidad de una conciencia madura y comprensiva.\n\nProyectas un halo de tolerancia ecuménica, sensibilidad moral y afecto universal. Cualquier criatura se siente dignificada ante ti, palpando un corazón limpio de altiveces de casta o fortuna.\n\nTu generosidad trasciende fronteras; mantén la ternura en el trato uno a uno para que tu amor universal se viva en la cercanía cotidiana de una amistad sincera y un amparo oportuno.`,

    11: `Tu presencia destila un magnetismo espiritual fascinante, una solemnidad intuitiva y una agudeza clarividente. A tu lado, las personas sienten que sus intenciones quedan al descubierto con benevolencia, despertando una veneración reverente.\n\nTu ser irradia una corriente electromagnética inspiradora. Tus reflexiones más casuales portan vislumbres proféticos, desarmando bloqueos anímicos y sembrando horizontes elevados en quien se cruza en tu camino.\n\nAterriza tu intensa carga intuitiva en palabras prácticas y sobriedad terrenal. Al traducir tus visiones con humildad y llaneza, tu luz se convierte en una guía segura y bienhechora en medio de la noche del mundo.`,

    22: `Proyectas la solidez arquitectónica de quien ha venido a erigir realidades maestras en beneficio de la sociedad. Quienes conversan contigo sienten de inmediato tu desdén por lo trivial y tu capacidad para concretar utopías en hechos reales.\n\nTu porte marida la amplitud del visionario con el cálculo riguroso del alarife. Tu palabra inspira certidumbre irrebatible, movilizando voluntades en torno a iniciativas colosales con una serenidad invulnerable.\n\nAcompaña tu imponente escala mental con paciencia didáctica hacia el ritmo de los demás. Al conceder tiempo a tu entorno para sintonizar con tus magnas concepciones, tu legado se cimenta sobre pilares de hermandad duradera.`,

    33: `Tu presencia social irradia consuelo, compasión sagrada y un amor incondicional que mitiga pesares. Caminas con la gracia de un guía ético cuya mirada reconforta, desarma rencores y recuerda a los demás su propia nobleza innata.\n\nTu proximidad se asemeja a un santuario en medio del trajín del siglo. Las almas heridas sienten un impulso instintivo de buscar tu amparo, sabiendo que en tu pecho hallarán acogida sin reproche y un bálsamo de esperanza.\n\nTu aura es una bendición colectiva; cultiva momentos de retiro silencioso para renovar la infinita fuente de afecto que compartes, perpetuando tu testimonio de santidad y caridad viva.`,
  },
};

export function getPersonalityDeep(num: number, lang: 'en' | 'pt' | 'es' = 'en', fullName?: string): string {
  const dict = PERSONALITY_INTERPRETATIONS[lang] || PERSONALITY_INTERPRETATIONS.en;
  const raw = dict[num] || dict[1]!;
  return fullName ? interpolateFirstName(raw, fullName) : raw;
}
