// Interpretacoes dos Padroes de Sombra e Desafios (Shadow and Challenges / Transmutations)
// Numeros 1 a 9 e Numeros Mestres 11, 22, 33 nos idiomas EN, PT e ES.
// Cada entrada contem 3 paragrafos substanciais separados por \n\n, estilo Carl Jung / Co-Star.

export const SHADOW_INTERPRETATIONS: Record<'en' | 'pt' | 'es', Record<number, string>> = {
  en: {
    1: `The shadow architecture of Number 1 manifests primarily as the tyrant of self-sufficiency or, inversely, the paralyzing dread of inadequacy. When operating under unconscious defense mechanisms, your ego interprets vulnerability as mortal danger, erecting an aggressive armor of stubborn pride, impatience, and unyielding intolerance for anyone else’s pace.\n\nIn interpersonal dynamics, this friction creates relational isolation. You may unconsciously steamroll collaborators, dismiss wise counsel out of a compulsive reflex to remain untouchable, or retreat into wounded arrogance when your unilateral vision encounters friction. The deeper shadow is the hidden fear that without sovereign dominance, you possess no intrinsic worth.\n\nThe conscious key to transmutation is discovering that authentic strength does not require isolation. When you allow yourself to be supported, practice receptive listening, and replace authoritarian control with collaborative empowerment, your fiery willpower transforms from a defensive flame into a warming hearth of true authority.`,

    2: `The shadow of Number 2 takes root in pathological over-accommodation, emotional codependency, and the covert manipulation of martyrdom. Because your psyche dreads discord and rejection above all else, you may systematically silence your authentic desires, assuming the false persona of the self-sacrificing caretaker who secretly harbors bitter resentment.\n\nThis repression frequently leaks out as passive-aggressive withdrawal, hypersensitivity to perceived slights, or indecisiveness masked as diplomacy. By projecting your own disowned power onto dominant partners, you risk becoming a perennial hostage to the moods of others, trapped in an endless cycle of overgiving followed by silent grievance.\n\nYour transmutation pathway requires reclaiming the sacred power of the word "No." When you understand that honest friction is infinitely healthier than synthetic peace, and when you erect firm boundaries around your emotional well-being, your empathy ceases to be a liability and becomes an unshakeable fortress of mature love.`,

    3: `The shadow trap of Number 3 manifests as superficial dispersion, compulsive performance, and the evasion of emotional gravity. Under ego defense, your sparkling communicative energy scatters across dozens of unfinished endeavors, using witty humor, charm, and social distraction as an intellectual shield against confronting inner melancholy or existential doubt.\n\nIn social spheres, this shadow surfaces as chronic gossip, a terror of being perceived as uninteresting, or cynical vanity. You may find yourself performing for external validation, burning out your nervous system in pursuit of constant applause while your deepest, most authentic creative voice remains neglected and unexpressed.\n\nTransmutation demands the courage of focused silence and emotional honesty. When you discipline your creative impulse, commit deeply to long-term craftsmanship, and allow yourself to be seen in your raw, unpolished truth without the need to entertain, your art touches timeless genius.`,

    4: `The shadow pattern of Number 4 crystallizes as emotional calcification, bureaucratic dogmatism, and an obsessive resistance to change. Driven by a deep-seated anxiety about scarcity and disorder, your psyche can transform order into a prison cell, becoming inflexible, hyper-critical, and terrified of spontaneity or unconventional thinking.\n\nIn work and relationships, this manifests as micromanagement, joyless workaholism, and an unbending insistence on doing things "the only correct way." You may sacrifice joy, intimacy, and evolution on the altar of predictability, punishing yourself and others with impossibly rigid standards of perfection.\n\nYour key to psychic transmutation is the conscious surrender of total control. When you recognize that genuine security is not built from rigid fortresses, but from faith in your inner resilience to adapt to life’s natural ebbs and flows, your discipline becomes a liberating foundation rather than a cage.`,

    5: `The shadow dynamic of Number 5 emerges as chronic escapism, sensory addiction, and a rebellious refusal to honor commitments. When threatened by routine or emotional depth, your ego mistakes stability for imprisonment, triggering an impulsive urge to burn bridges, change course abruptly, and flee from intimate accountability.\n\nRelationally, this pattern generates a trail of unfinished alliances, fragmented careers, and superficial acquaintances. You may chase fleeting novelty to outrun an internal vacuum, using restless travel, digital distractions, or hedonistic stimulation to avoid the quiet stillness where your soul confronts itself.\n\nTransmutation is unlocked when you discover internal freedom rather than geographic or circumstantial escape. When you learn to bring your vibrant curiosity into deep, disciplined focus and sustain fidelity to what matters most, your versatility matures into extraordinary wisdom and lasting impact.`,

    6: `The shadow architecture of Number 6 operates through smothering paternalism, self-righteous moral superiority, and the toxic burden of rescuing everyone. Convinced that only you understand what is good and virtuous for others, your ego can become intrusive, controlling, and deeply resentful when your unsolicited sacrifices are not met with total obedience.\n\nIn family and partnerships, this creates dynamic paralysis. By refusing to let others face the necessary consequences of their own choices, you infantilize those you claim to love, fostering weakness while secretly lamenting that you carry the weight of the world alone.\n\nYour evolutionary breakthrough occurs when you practice radical emotional detachment and surrender. When you accept that each soul’s journey belongs to them and that unconditional love honors other people’s autonomy, your protective warmth becomes a pure, non-possessive blessing.`,

    7: `The shadow of Number 7 manifests as intellectual arrogance, paranoid cynicism, and cold emotional isolation. Because the world often feels crass and overwhelming to your acute sensitivity, your ego retreats behind the intellectual walls of superiority, dismissing the emotional needs of others as irrational trivialities.\n\nIn daily life, this leads to profound alienation. You may over-analyze simple human interactions until all spontaneity is dissected to death, falling into spirals of existential dread, distrust, or reclusive aloofness. Underneath this intellectual fortress often lies a vulnerable heart that feels misunderstood and unloved.\n\nThe sacred transmutation for this shadow is opening the heart to human messiness. When you dare to step down from your ivory tower, embrace humility, and share your emotional vulnerability without the armor of intellectual detachment, your profound wisdom becomes a healing medicine for a searching world.`,

    8: `The shadow of Number 8 is the merciless pursuit of power, ruthless materialism, and the tragic terror of being dominated. Deeply wounded by early memories of helplessness or scarcity, your ego adopts the belief that life is a gladiatorial arena where you must either conquer or be crushed.\n\nIn leadership and intimacy, this shadow produces authoritarian bullying, transactional relationships, and an incapacity to show tenderness. You may measure human value strictly in terms of utility, financial net worth, or obedience, finding yourself isolated at the top of an empire surrounded by people who fear you rather than love you.\n\nYour key to psychic transmutation is discovering the majesty of spiritual stewardship and vulnerability. When you redirect your immense executive force to protect the weak, cultivate ethical abundance, and lead with heartfelt generosity, your authority transforms from tyranny into an enduring legacy of true honor.`,

    9: `The shadow of Number 9 crystallizes as spiritual elitism, bitter disillusionment with humanity, and a martyr complex that hides immense personal neglect. Because your ideals of brotherhood and justice are so celestial, the mundane flaws of real human beings can plunge you into chronic resentment, dramatic martyrdom, or passive aloofness.\n\nIn personal relationships, you may bestow universal affection on distant causes while ignoring the immediate emotional needs of those sitting right beside you. You can easily mistake personal avoidance for spiritual transcendence, using grand philosophical crusades to flee from messy, one-on-one accountability.\n\nYour path to liberation lies in embracing the sacred divinity of the imperfect here and now. When you release cosmic resentment, forgive the human condition for its stumbling pace, and practice humble, everyday kindness without preaching, your universal compassion becomes an eternal fountain of light.`,

    11: `The shadow pattern of Master Number 11 emerges as extreme nervous exhaustion, messianic delusion, and an ungrounded drift into psychic hypersensitivity. Because you channel an exceptionally high voltage of intuition, an untamed ego can mistake these impressions for personal infallibility, oscillating between spiritual pride and crushing imposter syndrome.\n\nWhen overwhelmed, this vibration collapses into debilitating anxiety, hypochondria, or erratic emotional turbulence. You may perceive malevolent energies everywhere, projecting your own unintegrated psychic shadows onto innocent surroundings while paralyzing yourself with fear of the mundane world.\n\nTransmutation demands disciplined physical grounding and psychological sobriety. Through daily somatic routines, simple physical labor, and humble emotional boundaries, you learn to step down your high psychic voltage safely, allowing your visionary gifts to illuminate the world without burning out your human vessel.`,

    22: `The shadow of Master Number 22 is the crushing paralysis of monumental ambition, megalomania, or cynical manipulation of institutional power. Faced with the staggering scale of your inner visions, you may succumb to the terror of inadequacy, burying your immense potential beneath mediocre routines while secretly despising the world for its limitations.\n\nIf expressed through egoic distortion, this energy turns Machiavellian: treating people as pawns on a chessboard, cutting ethical corners, and justifying destructive means for supposedly grand ends. The weight of your unmanifested potential can rot into bitter cynicism and destructive institutional sabotage.\n\nYour transmutation requires aligning supreme ambition with unbending ethical purity and humble, incremental steps. When you surrender the obsession with personal monuments and build patiently for the quiet, enduring benefit of human dignity, your monumental force reshapes history for the good of all.`,

    33: `The shadow of Master Number 33 is the perilous trap of the messiah complex, self-destructive martyrdom, and emotional burnout on an epic scale. Convinced that you alone must carry the sins and miseries of humanity, your ego can unconsciously invite betrayal and exploitation to validate your identity as the supreme sufferer.\n\nIn extreme manifestations, this generates deep spiritual pride masked as humble sacrifice. You may ignore your own physical and mental collapse, imposing your healing agendas onto people who have not asked for assistance, while fostering toxic dependency that keeps those around you permanently disabled.\n\nYour sacred key to transmutation is recognizing that you are not the savior of the universe, but a humble servant of love. When you practice fierce self-preservation, honor other souls’ sovereign right to their own karmic lessons, and pour your compassion from a full cup, your presence radiates pure divine healing without depletion.`,
  },
  pt: {
    1: `A arquitetura de sombra do Número 1 se manifesta como a tirania da autossuficiência ou, no polo oposto, o medo paralisante da inadequação. Quando seus mecanismos inconscientes de defesa assumem o controle, seu ego enxerga a vulnerabilidade como perigo mortal, erguendo uma couraça de orgulho inflexível, impaciência crônica e intolerância com o ritmo alheio.\n\nNas relações cotidianas, esse atrito gera isolamento afetivo. Você pode atropelar colaboradores sem perceber, rejeitar conselhos sábios por uma compulsão cega de parecer invulnerável ou se recolher em ressentimento quando sua vontade encontra limites. A raiz oculta dessa postura é o pavor de perder o valor próprio se não estiver no comando absoluto.\n\nA chave de transmutação é compreender que a verdadeira liderança não exige solidão. Ao permitir-se ser apoiado, praticar a escuta atenta e substituir o autoritarismo pela capacitação dos outros, sua vontade férrea deixa de ser uma labareda destrutiva e se transforma em uma fogueira acolhedora de autoridade madura.`,

    2: `A sombra do Número 2 se enraíza na concessão doentia, na dependência emocional e na chantagem sutil do martírio. Por temer a desarmonia e o abandono acima de todas as coisas, você pode silenciar repetidamente sua própria verdade, vestindo a máscara do salvador complacente que, no fundo, acumula uma silenciosa amargura.\n\nEssa repressão costuma vazar como passividade agressiva, melindre exagerado diante de críticas e indecisão crônica. Ao projetar seu próprio poder nas mãos de figuras dominantes, você corre o risco de viver como refém do humor alheio, preso no ciclo exaustivo de dar sem limites e depois cobrar afeto de forma indireta.\n\nSua via de transmutação exige resgatar o poder sagrado de dizer "Não". Quando você aceita que o atrito honesto é infinitamente mais curativo do que uma paz artificial e passa a defender seus próprios limites com firmeza, sua empatia deixa de ser fraqueza e se torna a mais sólida fortaleza de amor consciente.`,

    3: `A armadilha de sombra do Número 3 opera através da dispersão superficial, do perfeccionismo cênico e da fuga covarde do silêncio. Sob a pressão do ego, sua mente brilhante se divide em dezenas de iniciativas inacabadas, utilizando o humor sarcástico, as piadas e o carisma social como escudo para não encarar o vazio existencial ou a dor interior.\n\nNo ambiente social, essa sombra se expressa como fofoca, compulsão por aplausos externos e vaidade ansiosa. Você pode se desgastar tentando performar o tempo todo para ser o centro das atenções, esgotando sua energia vital enquanto sua voz artística mais profunda e autêntica permanece calada e sem foco.\n\nA transmutação exige a coragem da disciplina e da verdade sem filtros. Ao recolher sua imaginação em projetos de longo prazo, tolerar os períodos de quietude e aceitar ser visto em sua verdade crua — sem a obrigação de entreter ninguém —, sua criatividade alcança a genialidade atemporal.`,

    4: `O padrão de sombra do Número 4 se cristaliza como rigidez emocional, apego obsessivo a regras e pavor paralisante da mudança. Movido por uma angústia inconsciente de escassez e caos, seu ego transforma a ordem em prisão, tornando-se inflexível, julgador e hostil a qualquer ideia que fuja dos seus padrões pré-estabelecidos.\n\nNo trabalho e nos relacionamentos, isso se traduz em microgerenciamento, vício em trabalho desprovido de alegria e cobranças desumanas sobre si e sobre os demais. Você corre o risco de sacrificar o afeto, o descanso e a leveza no altar da previsibilidade, punindo quem ousa questionar seus métodos.\n\nO caminho de liberação é a entrega consciente ao fluxo vivo da realidade. Quando você descobre que a verdadeira segurança não nasce de fortalezas de concreto, mas da sua capacidade interior de responder com serenidade aos imprevistos, sua disciplina se torna a base de uma liberdade autêntica.`,

    5: `A dinâmica de sombra do Número 5 se revela na fuga compulsiva, no vício em adrenalina e na aversão neurótica ao compromisso. Sempre que a rotina ou a intimidade profunda ameaçam sua zona de conforto, seu ego confunde estabilidade com encarceramento, acionando o impulso impulsivo de quebrar pontes, sumir e recomeçar do zero.\n\nEssa inquietação deixa para trás um rastro de projetos inconclusos, laços afetivos desfeitos sem explicação e superficialidade crônica. Você pode correr o mundo para fugir de si mesmo, utilizando viagens, estímulos digitais ou excessos sensoriais para calar a voz da sua própria alma quando ela pede enraizamento.\n\nA transmutação desperta quando você compreende que a liberdade mais nobre é interior e não geográfica. Ao ancorar sua curiosidade eletrizante em causas nobres e sustentar a lealdade às escolhas que realmente importam, sua versatilidade deixa de ser fumaça e se transforma em sabedoria transformadora.`,

    6: `A sombra do Número 6 se manifesta no paternalismo sufocante, na superioridade moral e no complexo de salvador do mundo. Com a certeza inconsciente de que apenas você sabe o que é melhor para os outros, seu ego torna-se intrusivo, controlador e profundamente ressentido quando suas intromissões não são recebidas com gratidão servil.\n\nNas famílias e parcerias, isso cria uma dinâmica de invalidação alheia. Ao impedir que as pessoas enfrentem as consequências naturais de seus próprios erros, você adoece aqueles que jura proteger, alimentando dependências doentias enquanto se queixa de carregar o mundo nas costas.\n\nSua cura reside no desapego amoroso e na renúncia ao controle. Ao aceitar que cada ser humano possui seu próprio carma e seu próprio tempo de amadurecimento, e ao voltar seu zelo protetor para a sua própria vida, seu amor se liberta do veneno da posse e se torna pura bênção restauradora.`,

    7: `A sombra do Número 7 se manifesta na soberba intelectual, no ceticismo amargo e no isolamento gélido. Como o mundo sensorial costuma ferir sua extrema sensibilidade, seu ego se refugia em torres de arrogância acadêmica ou esotérica, tratando os sentimentos ordinários como fraquezas desprezíveis.\n\nIsso conduz a uma solidão corrosiva e paralisante. Você pode dissecar as pessoas com um bisturí analítico implacável até destruir qualquer espontaneidade relacional, mergulhando em crises de niilismo, desconfiança paranoica ou frieza calculada. Por trás dessa muralha de intelectualismo, quase sempre mora uma criança com medo de ser ferida.\n\nA transmutação sagrada para esta sombra é descer ao solo comum da humanidade. Ao ter a coragem de abrir o coração, aceitar a beleza imperfeita das relações e compartilhar suas dúvidas sem a armadura da infalibilidade, sua sabedoria deixa de ser uma lâmina fria e passa a acolher a alma do mundo.`,

    8: `O padrão de sombra do Número 8 é a obsessão por controle, a ganância predatória e o medo visceral da vulnerabilidade. Traumatizado por memórias precoces de impotência ou escassez, seu ego passa a acreditar que a vida é uma selva de sobrevivência onde quem não domina é inevitavelmente esmagado.\n\nNas relações e nos negócios, essa sombra gera posturas despóticas, frieza transacional e incapacidade de demonstrar ternura. Você pode passar a precificar pessoas com base exclusiva em utilidade, patrimônio ou subserviência, terminando isolado no topo de um império frio, cercado por colaboradores que temem sua fúria, mas não conhecem seu coração.\n\nA chave de transmutação é compreender a nobreza da generosidade e da vulnerabilidade. Ao consagrar sua formidável capacidade de comando para proteger os indefesos, criar empregos éticos e liderar pelo respeito e não pelo medo, seu poder material se eleva ao patamar de uma autoridade honrosa e inquestionável.`,

    9: `A sombra do Número 9 cristaliza-se no moralismo dogmático, na amargura com a mediocridade humana e na vitimização messiânica. Por carregar visões cósmicas grandiosas sobre justiça e perfeição, as mesquinharias do cotidiano podem precipitá-lo no cinismo, na apatia desdenhosa ou em cobranças irreais sobre aqueles que convivem com você.\n\nEm suas relações íntimas, você corre o risco de professar amor abstrato pela humanidade distante enquanto é ríspido, frio ou distante com os indivíduos ao seu lado. Você pode usar causas globais ou nobres ideais como desculpa sofisticada para fugir das responsabilidades afetivas imediatas do dia a dia.\n\nSeu caminho de libertação é aprender a amar a humanidade exatamente como ela é: tropeçando, imperfeita e em construção. Ao soltar a mágoa contra o mundo, acolher suas próprias falhas com ternura e praticar a bondade anônima e silenciosa nas pequenas coisas, sua compaixão cósmica se torna um sol inextinguível.`,

    11: `A sombra do Número Mestre 11 se revela no esgotamento nervoso extremo, na ilusão messiânica e na perda de contato com a realidade terrena. Por captar uma voltagem espiritual e psíquica desproporcional, seu ego pode se inflar de orgulho místico ou, no reverso da moeda, colapsar em crises agudas de ansiedade e síndrome de impostor.\n\nSem o aterramento necessário, essa vibração desliza para hipocondria, histeria emocional e desconfiança constante. Você pode enxergar conspirações e perigos invisíveis em toda parte, projetando suas próprias angústias não resolvidas sobre o ambiente e paralisando suas ações no mundo prático por excesso de estímulos.\n\nA transmutação exige aterramento corporal severo e sobriedade emocional. Por meio de rotinas simples, contato direto com a natureza e disciplina psicológica, você aprende a filtrar o excesso de voltagem, permitindo que sua intuição monumental guie os outros com serenidade, sem queimar os próprios circuitos.`,

    22: `A sombra do Número Mestre 22 se expressa na paralisia esmagadora diante da magnitude do próprio chamado, no cinismo pragmático ou na manipulação maquiavélica. Assustado pelo peso de suas próprias visões arquitetônicas, você pode se acovardar em rotinas medíocres, tornando-se amargo e destrutivo com o progresso alheio.\n\nQuando distorcida pelo ego, essa energia não mede escrúpulos para alcançar objetivos titânicos, tratando indivíduos como meros números ou engrenagens descartáveis. A frustração de não construir o que sonhou pode se degenerar em ressentimento corrosivo contra a sociedade e autodestruição.\n\nSua transmutação exige reconciliar a ambição de gigantes com a humildade do operário. Ao construir com paciência, passo a passo, sustentando princípios éticos incorruptíveis em cada tijolo assentado, sua potência sai do campo da ansiedade estéril e se consolida em obras eternas de amparo social.`,

    33: `A sombra do Número Mestre 33 é o abismo do complexo de salvador, o martírio autoprovocado e a falência energética provocada pela renúncia total de si mesmo. Acreditando inconscientemente que tem a obrigação de expiar as dores do mundo inteiro, seu ego atrai relações predatórias e traições para justificar seu papel de vítima sagrada.\n\nEm seus desvios mais graves, isso alimenta uma vaidade espiritual silenciosa que infantiliza os assistidos, gerando laços de dependência que impedem os outros de aprenderem com as próprias dores. Você pode ignorar a própria saúde e sanidade mental até o colapso absoluto.\n\nA chave sagrada de transmutação é reconhecer que você é apenas um canal do amor divino, e não o dono da redenção universal. Ao cultivar a preservação do seu corpo, respeitar o carma dos seus semelhantes e agir a partir de uma taça que transborda em vez de se esgotar, sua presença se consagra como puro remédio espiritual.`,
  },
  es: {
    1: `La sombra del Número 1 se manifiesta como la tiranía de la autosuficiencia o, en el polo opuesto, el pánico paralizante a no estar a la altura. Cuando los mecanismos reactivos del ego toman el mando, interpretas la vulnerabilidad como una amenaza letal, blindándote tras una coraza de orgullo rígido, impaciencia y desprecio hacia el ritmo ajeno.\n\nEn la convivencia, este patrón desemboca en el aislamiento afectivo. Tiendes a avasallar a quienes te rodean, a desestimar advertencias sensatas por el prurito de no mostrar flaqueza y a refugiarte en una altivez resentida ante el primer tropiezo. En el fondo, late el temor a perder valor propio si no ejerces un control unánime.\n\nLa transmutación requiere descubrir que la firmeza no está reñida con la ternura. Al dejarte cuidar, cultivar la escucha atenta y sustituir la imposición por la elevación de quienes te acompañan, tu indomable voluntad deja de ser un fuego devastador para erigirse en un hogar templado de liderazgo auténtico.`,

    2: `La sombra del Número 2 echa raíces en la sumisión neurótica, la dependencia emocional y la manipulación velada del victimismo. Por un pánico desmedido al conflicto y al repudio, silencias tus legítimos deseos bajo el ropaje del servidor abnegado que, en secreto, mastica un rencor amargo.\n\nEsta claudicación asoma como desdén pasivo-agresivo, susceptibilidad extrema y vacilación perpetua. Al transferir tu soberanía a figuras dominantes, te conviertes en rehén del humor ajeno, encerrándote en un circuito vicioso de entrega indiscriminada y reproche tácito.\n\nTu transmutación demanda recuperar la dignidad sagrada del "No". Cuando comprendes que una discrepancia franca es más saludable que una paz postiza y salvaguardas tus fronteras íntimas, tu empatía deja de ser sumisión y se transforma en un baluarte de afecto consciente.`,

    3: `La sombra del Número 3 se traduce en dispersión vana, histrionismo defensivo y pavor al vacío interior. Ante la zozobra existencial, tu inteligencia se fragmenta en proyectos truncados, recurriendo al chiste continuo, al sarcasmo y a la sociabilidad compulsiva como parapeto frente a la tristeza o la soledad.\n\nEn los vínculos, esto genera chismorreo, adicción al elogio y vanidad hueca. Derrochas energía intentando encandilar al auditorio mientras tu voz artística más genuina permanece postergada por temor al escrutinio formal.\n\nTu redención exige la disciplina del silencio y la honestidad radical. Al enfocar tu genio en obras maduras, tolerar la quietud y atreverte a mostrar tu fragilidad sin la careta del entretenimiento forzado, tu talento roza la genialidad perdurable.`,

    4: `La sombra del Número 4 deviene en cerrazón dogmática, rigor asfixiante y un terror patológico a la incertidumbre. Atormentado por el fantasma de la carencia y el desorden, tu ego convierte el orden en celda, volviéndose implacable, suspicaz y refractario a cualquier heterodoxia.\n\nEn lo laboral y lo íntimo, esto se plasma en perfeccionismo estéril, jornadas extenuantes y demandas intolerables hacia el prójimo. Corres el riesgo de inmolar el deleite, la espontaneidad y el afecto en el ara de la rutina, castigando a quien altere tus esquemas.\n\nLa llave liberadora es el abandono consciente al dinamismo de la vida. Cuando adviertes que la auténtica certidumbre no emana de bastiones inmutables, sino de tu solvencia interior para sortear los cambios, tu constancia pasa de cárcel a suelo firme de libertad creadora.`,

    5: `La sombra del Número 5 irrumpe como fuga sistemática, insaciabilidad sensorial y fobia al compromiso. Siempre que la regularidad o la intimidad exigen permanencia, tu mente confunde la quietud con la asfixia, precipitándote a dinamitar acuerdos y huir hacia lo desconocido.\n\nEsta agitación deja tras de sí una estela de vínculos inconclusos, faenas desiertas y superficialidad dispersa. Pretendes cruzar confines para evadirte de ti mismo, empleando mudanzas o placeres efímeros para silenciar el llamado del espíritu que suplica arraigo.\n\nLa transmutación amanece cuando comprendes que la libertad soberana es un estado interior y no una fuga geográfica. Al anclar tu asombro en propósitos trascendentes y mantener lealtad a lo que amas, tu versatilidad deja de ser un fuego fatuo y se convierte en sabiduría fecunda.`,

    6: `La sombra del Número 6 se disfraza de proteccionismo agobiante, santurronería moral y compulsión por redimir al prójimo. Convencido de que posees la medida exclusiva del bienestar ajeno, tu ego invade espacios, fiscaliza decisiones y guarda resentimiento cuando tus sacrificios no reciben sumisión incondicional.\n\nEn el seno familiar, esto invalida la madurez de los tuyos. Al evitarles las consecuencias aleccionadoras de sus propios desaciertos, atrofias la fuerza de quienes proclamas amar, fomentando ataduras enfermizas mientras te dueles de llevar el peso del mundo a cuestas.\n\nTu liberación exige soltar las riendas y respetar el destino del prójimo. Al asumir que cada alma debe librar sus propias batallas y al consagrar tu ternura a cultivar tu propio santuario, tu amor se limpia de posesividad y se derrama como puro bálsamo reconstituyente.`,

    7: `La sombra del Número 7 asoma en forma de altanería intelectual, suspicacia misantrópica y retraimiento desalmado. Dado que la crudeza del mundo agrede tu finura psíquica, tu ego se guarece en un escepticismo gélido, tachando las afecciones cotidianas de flaquezas inferiores.\n\nEsto engendra un aislamiento desolador. Tiendes a diseccionar el afecto hasta privarlo de calor, hundiéndote en espirales de desconfianza paranoide o esterilidad anímica. Tras ese despliegue de erudición arrogante, suele cobijarse un alma temerosa del rechazo.\n\nTu senda de transmutación radica en descender con piedad a la arena de la vida. Al atreverte a mostrar tu ternura, celebrar la bendita imperfección humana y compartir tus certezas sin aires pontificales, tu conocimiento deja de ser una hoja cortante y se convierte en luz consoladora para las almas.`,

    8: `La sombra del Número 8 se perfila como avidez despiadada, tiranía ejecutiva y pánico visceral a la fragilidad. Condicionado por viejas heridas de desamparo, tu ego asume la falacia de que la existencia es un coliseo donde es forzoso sojuzgar para no resultar sometido.\n\nEn los negocios y en el afecto, esta distorsión engendra tratos mercantilistas, aspereza insensible y fobia a la ternura. Tazas el valor de los seres por su rendimiento, su linaje o su obediencia, concluyendo confinado en la cima de un imperio inhóspito, rodeado de sirvientes timoratos pero huérfano de lealtad sincera.\n\nLa transmutación consiste en conciliar el poder con la piedad y la justicia distributiva. Al subordinar tu colosal vigor directivo al amparo de los postergados y al fomento de una prosperidad con rostro humano, tu jerarquía transmuta el temor en reverencia venerable.`,

    9: `La sombra del Número 9 cuaja en resentimiento amargo hacia la mediocridad humana, mesianismo herido y abandono de lo próximo. Al acariciar ideales utópicos sobre la hermandad cósmica, los defectos pedestres de la realidad cotidiana te precipitan en el desdén o en el reproche constante.\n\nEn tu círculo íntimo, corres el riesgo de proclamar un amor abstracto por la humanidad mientras tratas con frialdad a quienes comparten tu mesa. Te resulta cómodo ampararte en banderas ecuménicas para desatender las obligaciones afectivas directas que reclaman humildad y presencia terrenal.\n\nTu salvación pasa por abrazar con indulgencia la torpeza evolutiva del hombre. Al liquidar el rencor contra el mundo, aceptar tus propias inconsistencias y prodigar caridad silenciosa en los detalles mínimos de la vida, tu visión universal resplandece como un manantial inextinguible de concordia.`,

    11: `La sombra del Número Maestro 11 se expresa en crisis nerviosas devastadoras, delirios de predestinación y desconexión con la tierra. Al actuar como receptor de frecuencias espirituales descomunales, tu ego puede extraviarse en el orgullo iniciático o zozobrar en la angustia de un síndrome del impostor destructivo.\n\nSin arraigo biológico, esta corriente degenera en histeria, manías hipocondríacas y susceptibilidad asfixiante. Percibes sombras y conspiraciones en cualquier esquina, proyectando tu confusión psíquica sobre el entorno y quedando inerme para el combate cotidiano del mundo material.\n\nLa transmutación demanda una disciplina física y psicológica austera. Mediante labores manuales, hábitos templados y silencio mental, aprendes a metabolizar el voltaje trascendente, permitiendo que tu clarividencia disipe las tinieblas ajenas sin consumir tu organismo.`,

    22: `La sombra del Número Maestro 22 estriba en la parálisis abrumadora ante la magnitud de la propia tarea, el cinismo burocrático o la maquinación despótica. Amedrentado por las dimensiones cósmicas de tus planes, puedes desertar hacia la medianía, volviéndote amargado y destructivo ante las conquistas ajenas.\n\nCuando se corrompe, esta potencia no repara en estragos para coronar ambiciones titánicas, reduciendo a las personas a meros peones fungibles. La herida de no edificar lo vislumbrado puede agriarse en sabotaje institucional y nihilismo implacable.\n\nTu transmutación reclama maridar la audacia del estratega con la paciencia del artesano. Al poner la primera piedra sin soberbia, perseverando en la honradez irreprochable en cada eslabón de la obra, tu genio se materializa en baluartes invulnerables de bienestar para la humanidad.`,

    33: `La sombra del Número Maestro 33 es el escollo letal del mesianismo enfermizo, el martirio deliberado y la ruina psicofísica nacida de la anulación del propio ser. Convencido de que te atañe expiar los dolores del orbe, tu ego tolera vejaciones y deslealtades para reafirmar su condición de víctima sacrosanta.\n\nEn su extremo nocivo, esto nutre una soberbia espiritual silenciosa que incapacita a los auxiliados, tejiendo dependencias parasitarias que privan a los demás de aprender de sus propias pruebas. Llegas a quebrantar tu cuerpo y tu sosiego hasta el descalabro irremediable.\n\nEl secreto iniciático de tu transmutación radica en aceptar que no eres el salvador del cosmos, sino un instrumento transparente del amor divino. Al velar por tu propia salud, respetar la libertad evolutiva de cada alma y ofrecer tu compasión desde la plenitud, tu testimonio se consagra como una bendición inmortal.`,
  },
};
