// Interpretacoes Profundas do Desejo da Alma (Soul Urge - Motivacao Interior / Anima)
// Numeros 1 a 9 e Numeros Mestres 11, 22, 33 nos idiomas EN, PT e ES.
// Cada entrada contem 3 paragrafos substanciais separados por \n\n, estilo Carl Jung / Co-Star.

export const SOUL_URGE_INTERPRETATIONS: Record<'en' | 'pt' | 'es', Record<number, string>> = {
  en: {
    1: `Your soul hungers for sovereign independence and unconditioned creative freedom. In the silence of your core, beneath all social conditioning and obligations, you feel an imperative need to walk untrodden trails and forge your own destiny without seeking permission or external approval.\n\nYour inner essence rejects being governed or constrained by the opinions of others. You are motivated by the raw thrill of initiating original ideas and seeing your singular willpower leave a distinct imprint upon the world. Dependency of any kind feels suffocating to your psychic health.\n\nDeep fulfillment blooms when you trust your inner compass and take absolute ownership of your choices. When you align your fierce self-reliance with noble purpose, your solitary vision matures into an inspiring source of courage for others.`,

    2: `Your soul secretly longs for exquisite harmony, emotional reciprocity, and sacred connection. Inwardly, you crave environments of deep peace where mutual understanding flows without words, and where intimate partnerships and friendships are anchored in unshakeable loyalty.\n\nYour inner life is characterized by acute empathy and a visceral aversion to cruelty, discord, and division. You feel fulfilled not when you stand in the spotlight alone, but when you act as the intuitive heart of a union, weaving bridges of goodwill and dissolving friction with quiet gentleness.\n\nYour highest joy emerges when you act as an empathetic mediator without sacrificing your own boundaries. When you offer yourself the same tender care you lavish upon others, your soul becomes an inviolable sanctuary of tranquil wisdom.`,

    3: `Your soul yearns for radiant self-expression, joyful authenticity, and imaginative play. Behind every thought lies a deep, pulsing impulse to communicate beauty, awaken laughter, and illuminate the emotional landscape of everyone who crosses your path.\n\nIn your core, you wither in environments marked by joyless routine, emotional rigidity, or clinical coldness. You are spiritually fed by artistic exploration, playful conversation, poetic nuance, and the freedom to express your emotions without fear of judgment or censorship.\n\nInner fulfillment reaches its zenith when you release self-doubt and channel your vibrant imagination into meaningful creations. By turning your sparkling joy into a conscious offering, your spirit reminds the world of the sacred magic of existence.`,

    4: `Your soul seeks enduring solidity, sacred order, and psychological security. At your center lives an architect of reality who desires to construct foundations that stand the test of time, grounding ephemeral dreams into reliable, tangible structures.\n\nYour inner peace is deeply rooted in predictability, ethical integrity, and knowing that your world is built upon truth and meticulous craftsmanship. Chaos, deceit, and erratic behavior cause you intense psychic stress, prompting you to constantly restore stability and method.\n\nTrue contentment arrives when your daily discipline is sustained by loving purpose rather than anxiety. When you create a safe harbor where yourself and your loved ones can thrive with certitude, your soul rests in profound, quiet dignity.`,

    5: `Your soul craves untamed freedom, sensory exploration, and boundless evolution. Within your deepest layers lives an eternal adventurer who rejects rigid dogmas, hungering to experience the rich kaleidoscope of human culture, ideas, and sensory wonders.\n\nYou feel psychically imprisoned whenever life threatens to trap you in monotonous routines or restrictive expectations. Your spirit is nourished by movement, travel, spontaneous pivots, and the electric thrill of stepping into uncharted territory with wide-open curiosity.\n\nInner vitality surges when you embrace change as your natural element while discovering internal anchor points. When you transmute restless seeking into deep philosophical understanding, your freedom becomes a living catalyst of awakening for everyone you touch.`,

    6: `Your soul is driven by the sacred instinct to nurture, protect, and beautify the hearth of human existence. In quiet moments of reflection, you dream of creating sanctuary where unconditional love heals burdens and where family and community feel safe, cherished, and whole.\n\nYou feel a visceral responsibility for the emotional well-being of your tribe. Injustice, neglected children, broken homes, and aesthetic disharmony evoke a fierce protective response from your heart, compelling you to step forward as counselor, provider, and peacemaker.\n\nYour inner peace stabilizes when you balance selfless devotion with healthy boundaries. When you allow yourself to receive the very care you so generously offer to others, your home and heart become inexhaustible fountains of restorative grace.`,

    7: `Your soul pursues the sacred mystery, lucid solitude, and existential truth. In the inner sanctum of your psyche, you require silence and contemplation to pierce the veil of surface reality, deciphering the hidden metaphysical and scientific laws of the cosmos.\n\nYou are naturally allergic to superficial chitchat, commercial hype, and unquestioned dogma. Your inner life is rich, solitary, and philosophically rigorous; you find ecstasy in deep study, meditation, and communing with the profound elegance of nature and truth.\n\nGenuine fulfillment awakens when you honor your need for quiet retreats without drifting into cynical isolation. When you synthesize intellectual analysis with profound spiritual intuition, your solitary reflections illuminate the path for searching souls.`,

    8: `Your soul aspires to material mastery, executive authority, and sovereign stewardship. Deep down, you are called to wield worldly influence not out of petty vanity, but from a profound inner vocation to manifest prosperity, conquer obstacles, and build lasting systems of empowerment.\n\nYou respect competence, ambition, and strength. You feel a natural affinity for large-scale endeavors, understanding that capital and authority are sacred energetic currencies capable of transforming barren landscapes into thriving communities of opportunity.\n\nYour core settles into majesty when you align material ambition with moral integrity. When you direct your formidable command toward protecting the vulnerable and building ethical legacies, your soul experiences the supreme satisfaction of righteous power.`,

    9: `Your soul vibrates with universal compassion, artistic transcendence, and selfless love. At your essence, you belong to the cosmos rather than any single tribe, desiring to alleviate global suffering, complete karmic cycles, and inspire humanity through generous service.\n\nYou are deeply affected by world events, feeling the pain and triumphs of humanity as intimate occurrences in your own heart. Pettiness and greed bewilder you; your soul finds joy only when working for causes that elevate the dignity and consciousness of all beings.\n\nDeep peace envelopes you when you surrender attachment to personal credit and trust the cosmic flow. By offering your gifts freely without demanding reciprocal reward, your life becomes a selfless current of universal light.`,

    11: `Your soul carries the torch of high spiritual illumination, prophetic vision, and cosmic sensitivity. Inwardly, you register the subtle vibrational currents of the collective unconscious, feeling an urgent imperative to awaken higher consciousness in those around you.\n\nYou live in perpetual communion with archetypal realms, receiving profound flashes of intuitive revelation that defy linear explanation. You feel acute psychic friction when forced to conform to dull materialism or spiritually barren environments.\n\nFulfillment is found when you ground your supreme intuition into compassionate guidance. As you learn to navigate your electric psychic voltage with somatic calm, your soul acts as an unshakable lighthouse guiding humanity through spiritual storms.`,

    22: `Your soul envisions giant architectures that transform human civilization for generations. At your center lives the Master Builder, hungering to bridge cosmic ideals with massive, tangible engineering in the physical world.\n\nYou are not satisfied with small dreams; your soul feels a sacred duty to tackle planetary challenges—infrastructure, ecological restoration, global education, and systems that lift millions out of poverty and stagnation.\n\nYour soul finds rest only in noble, monumental execution. When you place your colossal organizational genius at the altar of universal welfare, your hands build monuments of progress that endure across the centuries.`,

    33: `Your soul radiates the highest octave of unconditional devotion, Christic healing, and universal solace. Within your core beats an infinite reservoir of empathy dedicated to comforting the afflicted and elevating the spiritual frequency of humanity.\n\nYou are drawn like a magnet to suffering, carrying the innate capacity to disarm hatred and restore fractured spirits through the sheer purity of your loving presence. You yearn to teach not through words, but through the living grace of your compassion.\n\nYour ultimate fulfillment unfolds as you embody compassionate wisdom without falling into martyrdom. When you sustain your healing devotion with sacred self-preservation, your soul radiates an eternal balm that elevates human consciousness toward the divine.`,
  },
  pt: {
    1: `Sua alma anseia por independência soberana e liberdade criativa incondicionada. No silêncio do seu íntimo, despido de condicionamentos sociais e obrigações mundanas, você sente a necessidade imperativa de abrir caminhos virgens e forjar o próprio destino sem pedir permissão ou validação externa.\n\nSua essência interior rejeita com veemência ser governada por regras arbitrárias ou convenções estreitas. Você é nutrido pela emoção visceral de originar ideias pioneiras e ver sua vontade individual deixar uma marca indelével na realidade. A dependência de qualquer natureza parece um cativeiro para a sua psique.\n\nA plenitude autêntica floresce quando você confia na sua bússola íntima e assume a autoria absoluta das suas escolhas. Ao colocar sua determinação a serviço de causas nobres, sua visão solitária se converte em uma fonte inesgotável de coragem e inspiração para os que o cercam.`,

    2: `Sua alma anseia secretamente por harmonia profunda, reciprocidade afetiva e conexões de alma. No seu íntimo mais silencioso, você busca refúgios de serenidade onde a compreensão mútua aconteça sem a necessidade de palavras e onde as parcerias sejam sustentadas pela lealdade inabalável.\n\nSua vida interior é pautada por uma empatia aguda e por uma aversão orgânica à crueldade, aos conflitos ruidosos e às rupturas desnecessárias. Você não se realiza no isolamento ou no estrelato solitário, mas ao atuar como o coração unificador de parcerias e comunidades acolhedoras.\n\nSua maior bem-aventurança surge ao agir como mediador amoroso sem abrir mão dos próprios limites. Quando você dedica ao seu próprio ser o mesmo carinho que oferece aos outros, sua alma se estabelece como um porto seguro de paz e sabedoria restauradora.`,

    3: `Sua alma vibra pela autoexpressão espontânea, autenticidade efervescente e imaginação fértil. Por trás de cada reflexão existe o impulso vital de comunicar beleza, semear alegria e colorir a experiência humana daqueles que cruzam o seu caminho.\n\nEm seu íntimo, você definha em ambientes marcados por rotinas frias, formalidades excessivas ou rigidez emocional. Sua alma se alimenta do contato com a arte, de diálogos inteligentes, do riso descontraído e da liberdade absoluta de manifestar suas emoções sem medo da reprovação alheia.\n\nA realização íntima floresce quando você supera a insegurança e canaliza sua energia viva em projetos de significado duradouro. Ao colocar seu encanto e sensibilidade a serviço da elevação moral do mundo, seu espírito resgata a magia e o entusiasmo de viver.`,

    4: `Sua alma busca solidez inabalável, ordem sagrada e segurança existencial. No seu centro reside o arquétipo do construtor de realidades, aquele que deseja edificar alicerces capazes de resistir ao teste dos séculos, transformando sonhos dispersos em estruturas confiáveis e tangíveis.\n\nSua paz interior depende da previsibilidade, da honradez e da certeza de que suas realizações foram forjadas com rigor ético e capricho minucioso. O caos, a mentira e a instabilidade provocam em você um desconforto agudo, instigando-o a restaurar a ordem e a clareza prática.\n\nO contentamento genuíno surge quando sua rotina reflete disciplina amorosa em vez de ansiedade. Ao oferecer um solo firme e seguro sobre o qual você e seus entes queridos possam florescer com tranquilidade, sua alma repousa em uma dignidade inquestionável.`,

    5: `Sua alma anseia por liberdade irrevogável, expansão contínua e aventura existencial. Dentro das suas camadas mais profundas mora um espírito peregrino avesso a prisões dogmáticas, sedento por experimentar a multiplicidade do mundo, suas culturas e seus mistérios.\n\nVocê se sente sufocado sempre que a vida ameaça prendê-lo a rotinas monótonas ou obrigações sufocantes. Sua energia espiritual se renova com o movimento, as viagens, as quebras de paradigma e a vertigem eletrizante de se lançar ao desconhecido com os olhos cheios de curiosidade.\n\nSua vitalidade interior atinge o ápice quando você descobre que a verdadeira liberdade é um estado de consciência interior. Ao ancorar sua curiosidade em compreensões profundas sobre a vida, sua inquietude se transforma em pura sabedoria e catalisador de evolução para os outros.`,

    6: `Sua alma é movida pelo chamado sagrado de proteger, acolher e harmonizar os laços humanos. Nos momentos de introspecção, você aspira a criar santuários onde o amor cure feridas emocionais e onde a família e a comunidade se sintam plenamente seguras, cuidadas e integradas.\n\nSeu coração experimenta uma responsabilidade quase física pelo bem-estar das pessoas ao seu redor. A desordem, o desamparo, a negligência afetiva e a injustiça mobilizam sua coragem protetora, impulsionando-o a agir como conselheiro, guardião e restaurador da dignidade humana.\n\nA serenidade interior se consolida quando você equilibra a dedicação aos outros com o respeito às suas próprias necessidades. Ao permitir-se receber o mesmo cuidado que distribui, seu templo pessoal permanece fértil e seu amor se torna uma fonte eterna de concórdia.`,

    7: `Sua alma persegue o mistério velado, a solitude lúcida e as verdades essenciais da existência. No recesso mais íntimo da sua psique, você necessita de silêncio para decifrar as leis invisíveis que regem a vida, a mente e o universo.\n\nVocê possui uma aversão natural à superficialidade, ao barulho dos modismos e a dogmas cegos. Sua vida íntima é profunda e contemplativa; sua maior alegria reside no estudo concentrado, na meditação e no diálogo solitário com a imensidão da natureza e da sabedoria eterna.\n\nA plenitude autêntica surge quando você honra seus momentos de retiro sem se perder na amargura ou no isolamento cético. Ao unir o rigor analítico à intuição espiritual profunda, seus insights silenciosos se tornam remédio e luz para mentes desorientadas.`,

    8: `Sua alma almeja maestria material, liderança executiva e soberania prática. No fundo, você é chamado a exercer autoridade transformadora no mundo físico não por vaidade efêmera, mas pela vocação nobre de materializar abundância, superar obstáculos e erguer sistemas duradouros de progresso.\n\nVocê respeita a competência, a audácia e a firmeza de caráter. Sua consciência compreende intuitivamente que os recursos financeiros e o poder institucional são energias dinâmicas destinadas a serem governadas com sabedoria, ética e justiça distributiva.\n\nSeu eixo se estabiliza em verdadeira grandeza quando você alinha a ambição material a propósitos humanitários elevados. Ao empregar sua força executiva para criar oportunidades dignas e amparar o crescimento alheio, sua alma experimenta a realização do poder legítimo.`,

    9: `Sua alma ressoa com compaixão universal, desapego maduro e fraternidade cósmica. No cerne do seu ser, você pertence à totalidade da vida, desejando amenizar o sofrimento humano, redimir cicatrizes cármicas e inspirar o mundo através de uma entrega generosa e desinteressada.\n\nAs dores e vitórias da humanidade repercutem diretamente no seu coração. A mesquinhez e o egoísmo parecem estranhos à sua natureza; sua alma encontra repouso apenas quando se consagra a causas que elevam a dignidade, a justiça e a consciência coletiva.\n\nA paz profunda envolve seu espírito quando você atua com desprendimento de méritos pessoais e confia no fluxo universal. Ao doar seus talentos sem esperar recompensas exclusivas, sua vida se converte em uma corrente cristalina de inspiração cósmica.`,

    11: `Sua alma carrega a tocha da iluminação espiritual, da visão profética e da sensibilidade arquetípica. No íntimo, você capta em tempo real as correntes sutis do inconsciente coletivo, sentindo o chamado inegociável de despertar clareza nos corações humanos.\n\nVocê habita um estado de contato direto com dimensões elevadas da consciência, recebendo lampejos intuitivos que desafiam a lógica cartesiana. Ambientes espiritualmente estéreis ou puramente mecanicistas geram em sua psique um desconforto profundo e imediato.\n\nA realização reside em aterrar sua intuição divina em conselhos serenos e atitudes práticas. Ao metabolizar sua voltagem psíquica com equilíbrio emocional e simplicidade diária, sua alma se firma como farol luminoso em meio às névoas do mundo.`,

    22: `Sua alma sonha com obras monumentais que sirvam à evolução humana por gerações. No seu núcleo habita o Mestre Arquiteto, desejoso de converter visões ideais em monumentos práticos, tecnologias sustentáveis e instituições de amparo duradouro.\n\nPlanos pequenos não encontram ressonância em seu peito; sua alma sente a responsabilidade cósmica de encarar desafios estruturais de grande envergadura, construindo sistemas que libertem comunidades e abram caminhos para o futuro da sociedade.\n\nSua alma encontra descanso na magnitude e na integridade. Ao colocar sua capacidade estratégica a serviço do bem comum, suas mãos edificam marcos de progresso que permanecerão de pé muito depois da sua passagem pela Terra.`,

    33: `Sua alma irradia a frequência crística da compaixão curadora, do consolo universal e da caridade sublime. Dentro de você pulsa uma fonte inesgotável de afeto voltada a confortar os corações quebrantados e lembrar a cada ser humano a santidade da sua própria vida.\n\nVocê é atraído espontaneamente pelo sofrimento alheio, portando o dom de desarmar ressentimentos antigos e restaurar espíritos feridos através do calor da sua pura presença amorosa. Seu ensino não reside em teorias, mas na prática diária do perdão e da ternura.\n\nSeu propósito se consuma ao encarnar a sabedoria do coração sem se deixar arrastar pelo martírio. Ao cuidar do seu próprio templo com limites saudáveis, sua luz permanece eterna, regenerando a alma do mundo.`,
  },
  es: {
    1: `Tu alma anhela independencia soberana y libertad creadora absoluta. En el silencio de tu centro, despojado de exigencias sociales y ataduras heredadas, sientes la necesidad imperativa de abrir caminos vírgenes y forjar tu destino sin pedir permiso ni depender de aprobación externa.\n\nTu íntima naturaleza rechaza con vigor ser gobernada por criterios ajenos. Te vivifica el ardor de encender iniciativas inéditas y contemplar cómo tu voluntad imprime una huella nítida en la realidad. La subordinación o la pasividad resultan asfixiantes para tu psique.\n\nLa plenitud nace cuando confías en tu brújula interior y asumes la autoría total de tus elecciones. Al orientar tu firmeza hacia metas nobles, tu visión solitaria amanece como un manantial de coraje e inspiración para quienes te rodean.`,

    2: `Tu alma busca secretamente armonía profunda, reciprocidad sensible y lazos sagrados. En tu interior más sosegado, ansías espacios de serenidad donde la comprensión fluya sin necesidad de palabras y donde las alianzas se construyan sobre una lealtad incondicional.\n\nTu vida afectiva se rige por una empatía prodigiosa y un rechazo instintivo a la hostilidad, los pleitos vanos y las divisiones. No hallas regocijo en el brillo solitario, sino en obrar como el corazón pacificador que teje concordia y disuelve tensiones con delicadeza.\n\nTu gozo más alto florece al obrar como puente empático sin renunciar a tus propios límites. Cuando te brindas a ti mismo la ternura que dispensas a los demás, tu alma se convierte en un refugio inexpugnable de paz y sosiego.`,

    3: `Tu alma vibra con la autoexpresión luminosa, el entusiasmo sincero y la alegría creativa. Detrás de cada pensamiento palpita el deseo de transmitir belleza, avivar el ánimo colectivo y colorear la experiencia de quienes comparten tu camino.\n\nEn tu centro, languideces en entornos dominados por el tedio, la frialdad o la censura emocional. Tu espíritu se alimenta del arte, la tertulia ingeniosa, la gracia verbal y la libertad irrestricta de manifestar tu verdad sin temor al reproche.\n\nLa realización interna se despierta cuando disuelves la vacilación y viertes tu talento en obras de alcance duradero. Al consagrar tu encanto a elevar la moral del mundo, tu testimonio despierta la esperanza y el asombro por la vida.`,

    4: `Tu alma busca estabilidad inquebrantable, orden metódico y seguridad existencial. En tu raíz habita el arquitecto de realidades, deseoso de edificar estructuras que desafíen el paso de las eras, aterrizando conceptos etéreos en cimientos sólidos y confiables.\n\nTu paz depende de la certidumbre, la rectitud y la certeza de que tu obra se levanta sobre la honradez y la maestría artesanal. El caos y la falsedad generan en ti una desazón profunda, incitándote a restaurar la coherencia y el método.\n\nLa satisfacción verdadera florece cuando tu disciplina cotidiana se nutre de amor y no de ansiedad. Al brindar un puerto seguro donde los tuyos puedan prosperar con certeza, tu alma se asienta en una dignidad serena e inmutable.`,

    5: `Tu alma clama por libertad expansiva, mudanza estimulante y aventura existencial. En tus profundidades habita un espíritu viajero que rechaza las fórmulas estériles, sediento de explorar los infinitos matices de la vida y el saber directo.\n\nTe sientes cautivo cuando la rutina pretende encasillarte en moldes asfixiantes. Tu vitalidad resurge con el movimiento, los horizontes nuevos, el contraste cultural y el vértigo electrizante de asomarte a lo desconocido con el alma abierta.\n\nTu espíritu alcanza plenitud cuando descubres que la libertad suprema es un estado de madurez interior. Al canalizar tu curiosidad en saberes trascendentes, tu dinamismo se transforma en una palanca liberadora para todo tu entorno.`,

    6: `Tu alma está llamada a proteger, embellecer y armonizar los vínculos esenciales. En el silencio de tu ser, anhelas forjar refugios donde el afecto sane heridas y donde la familia y la comunidad florezcan bajo el amparo del amor leal.\n\nExperimentas una responsabilidad viva por la ventura de los tuyos. El desamparo, el dolor ajeno y la desavenencia conmueven tus fibras íntimas, exhortándote a obrar como tutor, mediador y custodio de la dignidad humana.\n\nLa paz interior se estabiliza cuando equilibras la entrega a los demás con el debido cuidado de tu propio ser. Al permitirte ser arropado en la misma medida en que te donas, tu manantial afectivo resplandece inagotable.`,

    7: `Tu alma persigue el misterio velado, la soledad lúcida y la verdad trascendente. En el santuario de tu psique, requieres silencio y contemplación para descifrar las leyes profundas que gobiernan la existencia, la mente y el orden cósmico.\n\nEres alérgico a la vulgaridad, al ruido ensordecedor del mundo y a los dogmas irreflexivos. Tu vida íntima es sobria, erudita y ascética; encuentras deleite supremo en el estudio minucioso, la meditación y el diálogo a solas con el enigma de lo creado.\n\nLa plenitud genuina se revela cuando honras tus retiros reflexivos sin deslizarte hacia el aislamiento amargo. Al tender un puente entre tu saber contemplativo y la necesidad ajena, tus revelaciones iluminan la senda de los extraviados.`,

    8: `Tu alma aspira a la maestría material, la visión ejecutiva y el liderazgo justo. En el fondo, estás llamado a ejercer influencia en el mundo físico para materializar abundancia, derribar obstáculos y forjar sistemas perdurables de progreso colectivo.\n\nReconozcas la destreza, el valor y el temple de espíritu. Comprendes con naturalidad que el poder y los recursos económicos son corrientes vivas concebidas para ser gobernadas con rectitud, sabiduría y sentido social.\n\nTu eje alcanza grandeza cuando alineas la ambición práctica con principios éticos nobles. Al consagrar tu capacidad directiva a levantar a los vulnerables y multiplicar el bienestar, tu alma saborea la gloria de la autoridad legítima.`,

    9: `Tu alma resuena con compasión universal, desapego sereno y fraternidad trascendente. En tu núcleo, perteneces a la anchura del orbe, aspirando a disolver el dolor ajeno, cerrar cuentas cármicas y ensalzar la condición humana a través del servicio generoso.\n\nEl sufrimiento y las esperanzas del mundo repercuten en tu pecho con fuerza fraternal. La mezquindad te resulta extraña; tu alma únicamente descansa cuando milita en causas consagradas a ensanchar la luz, la justicia y la concordia de los pueblos.\n\nLa serenidad profunda te abraza cuando actúas sin apego al reconocimiento personal y te abandonas al flujo cósmico. Al entregar tus caudales sin reclamar dividendos, tu existencia se erige en un faro eterno de inspiración.`,

    11: `Tu alma porta la llama de la visión espiritual, la intuición suprema y la resonancia profética. Registras las corrientes sutiles de la conciencia colectiva, experimentando el mandato imperioso de despertar lucidez y serenidad en quienes buscan orientación.\n\nHabitas en vecindad constante con los arquetipos superiores, recibiendo vislumbres que escapan a la formulación empírica. El materialismo obtuso y los entornos espiritualmente yermos te provocan una profunda opresión psíquica.\n\nTu plenitud se concreta al anclar tu visión en palabras sabias y actos compasivos. Al sosegar tu torrente intuitivo mediante la disciplina cotidiana, tu alma actúa como un faro inextinguible en medio de las mareas del tiempo.`,

    22: `Tu alma sueña con obras titánicas que beneficien a generaciones enteras. En tu esencia vive el Maestro Constructor, anhelando fusionar grandes ideales civilizatorios con estructuras tangibles, tecnologías sostenibles y organismos perdurables.\n\nLas empresas modestas no conmueven tu pecho; tu alma asume el encargo sagrado de domeñar complejidades logísticas mayúsculas, alzando obras que emancipen pueblos y abran horizontes al mañana de la sociedad.\n\nTu alma se realiza al convertir utopías en realidades prácticas al servicio del bien común. Cuando tu descomunal vigor directivo se rinde a la rectitud, tus manos construyen monumentos que perdurarán a través de las edades.`,

    33: `Tu alma irradia la frecuencia crística del amor desinteresado, el consuelo universal y la redención compasiva. Posees un manantial inagotable de empatía para mitigar el sufrimiento y recordar a cada ser humano la sacralidad de su propio destino.\n\nAcudes espontáneamente allá donde late el dolor, dotado de la gracia de desarmar rencores y restañar ánimos quebrantados con el calor de tu cercanía. Tu doctrina es el testimonio transparente de la caridad y la piedad activa.\n\nTu misión se corona cuando encarnas la ternura sabia sin despeñarte en el martirio estéril. Al resguardar tu templo con prudencia, tu llama permanece inmortal, consolando y sanando el alma del mundo.`,
  },
};

export function getSoulUrgeDeep(num: number, lang: 'en' | 'pt' | 'es' = 'en'): string {
  const dict = SOUL_URGE_INTERPRETATIONS[lang] || SOUL_URGE_INTERPRETATIONS.en;
  return dict[num] || dict[1]!;
}
